/*
 * PrimalSolver - a convex optimization solver in C99 (LP/QP/SOCP/SDP/exp-power/MIP).
 * Copyright 2026 Gaetano Minardi
 * SPDX-License-Identifier: Apache-2.0
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  A copy of the License
 * is in the repository root (LICENSE) and at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
/* primal_info.c - information items and the symbolic-constant table.
 * Verbatim split of primal.c: no logic change. Shares primal_priv.h.
 */
#include "primal_priv.h"

/* ======================================================================
 * Symbolic constants (reference MSK_getsymbcondim/MSK_getsymbcon/
 * MSK_symnamtovalue/MSK_iparvaltosymnam). The table is the one of reference
 * 11.2.4, EXTRACTED from its own library by calling
 * MSK_getsymbcondim/MSK_getsymbcon (1438 entries, maxlen 60) -- not invented.
 * MSK_symnamtovalue writes the value as a decimal string and answers 1 if the
 * name exists; MSK_iparvaltosymnam writes "" where a parameter has no symbolic
 * name, exactly as the reference does (measured).
 * ====================================================================== */
#define PRIMAL_SYMB_N 1438
#define PRIMAL_SYMB_MAXLEN 60
static const char *const symbcon_names[PRIMAL_SYMB_N] = {
    "MSK_BI_NEVER", "MSK_BI_ALWAYS", "MSK_BI_NO_ERROR", "MSK_BI_IF_FEASIBLE",
    "MSK_BI_RESERVERED", "MSK_BK_LO", "MSK_BK_UP", "MSK_BK_FX", "MSK_BK_FR", "MSK_BK_RA",
    "MSK_MARK_LO", "MSK_MARK_UP", "MSK_SIM_PRECISION_NORMAL", "MSK_SIM_PRECISION_EXTENDED",
    "MSK_SIM_DEGEN_NONE", "MSK_SIM_DEGEN_FREE", "MSK_SIM_DEGEN_AGGRESSIVE",
    "MSK_SIM_DEGEN_MODERATE", "MSK_SIM_DEGEN_MINIMUM", "MSK_TRANSPOSE_NO", "MSK_TRANSPOSE_YES",
    "MSK_UPLO_LO", "MSK_UPLO_UP", "MSK_SIM_REFORMULATION_ON", "MSK_SIM_REFORMULATION_OFF",
    "MSK_SIM_REFORMULATION_FREE", "MSK_SIM_REFORMULATION_AGGRESSIVE",
    "MSK_SIM_EXPLOIT_DUPVEC_ON", "MSK_SIM_EXPLOIT_DUPVEC_OFF", "MSK_SIM_EXPLOIT_DUPVEC_FREE",
    "MSK_SIM_HOTSTART_NONE", "MSK_SIM_HOTSTART_FREE", "MSK_SIM_HOTSTART_STATUS_KEYS",
    "MSK_INTPNT_HOTSTART_NONE", "MSK_INTPNT_HOTSTART_PRIMAL", "MSK_INTPNT_HOTSTART_DUAL",
    "MSK_INTPNT_HOTSTART_PRIMAL_DUAL", "MSK_CALLBACK_BEGIN_ROOT_CUTGEN",
    "MSK_CALLBACK_IM_ROOT_CUTGEN", "MSK_CALLBACK_END_ROOT_CUTGEN",
    "MSK_CALLBACK_BEGIN_SOLVE_ROOT_RELAX", "MSK_CALLBACK_END_SOLVE_ROOT_RELAX",
    "MSK_CALLBACK_BEGIN_OPTIMIZER", "MSK_CALLBACK_END_OPTIMIZER", "MSK_CALLBACK_BEGIN_FOLDING",
    "MSK_CALLBACK_END_FOLDING", "MSK_CALLBACK_BEGIN_FOLDING_BI",
    "MSK_CALLBACK_BEGIN_FOLDING_BI_INITIALIZE", "MSK_CALLBACK_END_FOLDING_BI_INITIALIZE",
    "MSK_CALLBACK_BEGIN_FOLDING_BI_PRIMAL", "MSK_CALLBACK_FOLDING_BI_PRIMAL",
    "MSK_CALLBACK_END_FOLDING_BI_PRIMAL", "MSK_CALLBACK_BEGIN_FOLDING_BI_DUAL",
    "MSK_CALLBACK_FOLDING_BI_DUAL", "MSK_CALLBACK_END_FOLDING_BI_DUAL",
    "MSK_CALLBACK_BEGIN_FOLDING_BI_OPTIMIZER", "MSK_CALLBACK_FOLDING_BI_OPTIMIZER",
    "MSK_CALLBACK_END_FOLDING_BI_OPTIMIZER", "MSK_CALLBACK_END_FOLDING_BI",
    "MSK_CALLBACK_BEGIN_PRESOLVE", "MSK_CALLBACK_UPDATE_PRESOLVE", "MSK_CALLBACK_END_PRESOLVE",
    "MSK_CALLBACK_BEGIN_INTPNT", "MSK_CALLBACK_INTPNT", "MSK_CALLBACK_END_INTPNT",
    "MSK_CALLBACK_BEGIN_CONIC", "MSK_CALLBACK_CONIC", "MSK_CALLBACK_END_CONIC",
    "MSK_CALLBACK_PRIMAL_SIMPLEX", "MSK_CALLBACK_DUAL_SIMPLEX", "MSK_CALLBACK_BEGIN_BI",
    "MSK_CALLBACK_END_BI", "MSK_CALLBACK_BEGIN_INITIALIZE_BI",
    "MSK_CALLBACK_END_INITIALIZE_BI", "MSK_CALLBACK_BEGIN_PRIMAL_BI",
    "MSK_CALLBACK_UPDATE_PRIMAL_BI", "MSK_CALLBACK_END_PRIMAL_BI",
    "MSK_CALLBACK_BEGIN_DUAL_BI", "MSK_CALLBACK_UPDATE_DUAL_BI", "MSK_CALLBACK_END_DUAL_BI",
    "MSK_CALLBACK_BEGIN_OPTIMIZE_BI", "MSK_CALLBACK_OPTIMIZE_BI",
    "MSK_CALLBACK_END_OPTIMIZE_BI", "MSK_CALLBACK_BEGIN_PRIMAL_SIMPLEX_BI",
    "MSK_CALLBACK_UPDATE_PRIMAL_SIMPLEX_BI", "MSK_CALLBACK_END_PRIMAL_SIMPLEX_BI",
    "MSK_CALLBACK_BEGIN_DUAL_SIMPLEX_BI", "MSK_CALLBACK_UPDATE_DUAL_SIMPLEX_BI",
    "MSK_CALLBACK_END_DUAL_SIMPLEX_BI", "MSK_CALLBACK_END_SIMPLEX_BI",
    "MSK_CALLBACK_BEGIN_MIO", "MSK_CALLBACK_IM_MIO", "MSK_CALLBACK_NEW_INT_MIO",
    "MSK_CALLBACK_END_MIO", "MSK_CALLBACK_RESTART_MIO", "MSK_CALLBACK_DECOMP_MIO",
    "MSK_CALLBACK_BEGIN_SIMPLEX", "MSK_CALLBACK_IM_SIMPLEX", "MSK_CALLBACK_UPDATE_SIMPLEX",
    "MSK_CALLBACK_BEGIN_DUAL_SIMPLEX", "MSK_CALLBACK_IM_DUAL_SIMPLEX",
    "MSK_CALLBACK_UPDATE_DUAL_SIMPLEX", "MSK_CALLBACK_END_DUAL_SIMPLEX",
    "MSK_CALLBACK_BEGIN_PRIMAL_SIMPLEX", "MSK_CALLBACK_IM_PRIMAL_SIMPLEX",
    "MSK_CALLBACK_UPDATE_PRIMAL_SIMPLEX", "MSK_CALLBACK_END_PRIMAL_SIMPLEX",
    "MSK_CALLBACK_END_SIMPLEX", "MSK_CALLBACK_BEGIN_INFEAS_ANA", "MSK_CALLBACK_END_INFEAS_ANA",
    "MSK_CALLBACK_IM_PRIMAL_SENSIVITY", "MSK_CALLBACK_IM_DUAL_SENSIVITY",
    "MSK_CALLBACK_IM_MIO_INTPNT", "MSK_CALLBACK_IM_MIO_PRIMAL_SIMPLEX",
    "MSK_CALLBACK_IM_MIO_DUAL_SIMPLEX", "MSK_CALLBACK_BEGIN_PRIMAL_SETUP_BI",
    "MSK_CALLBACK_END_PRIMAL_SETUP_BI", "MSK_CALLBACK_BEGIN_DUAL_SETUP_BI",
    "MSK_CALLBACK_END_DUAL_SETUP_BI", "MSK_CALLBACK_BEGIN_PRIMAL_SENSITIVITY",
    "MSK_CALLBACK_END_PRIMAL_SENSITIVITY", "MSK_CALLBACK_BEGIN_DUAL_SENSITIVITY",
    "MSK_CALLBACK_END_DUAL_SENSITIVITY", "MSK_CALLBACK_BEGIN_LICENSE_WAIT",
    "MSK_CALLBACK_END_LICENSE_WAIT", "MSK_CALLBACK_IM_LICENSE_WAIT",
    "MSK_CALLBACK_BEGIN_QCQO_REFORMULATE", "MSK_CALLBACK_QO_REFORMULATE",
    "MSK_CALLBACK_END_QCQO_REFORMULATE", "MSK_CALLBACK_BEGIN_TO_CONIC",
    "MSK_CALLBACK_END_TO_CONIC", "MSK_CALLBACK_BEGIN_PRIMAL_REPAIR",
    "MSK_CALLBACK_END_PRIMAL_REPAIR", "MSK_CALLBACK_BEGIN_READ", "MSK_CALLBACK_IM_READ",
    "MSK_CALLBACK_END_READ", "MSK_CALLBACK_BEGIN_WRITE", "MSK_CALLBACK_END_WRITE",
    "MSK_CALLBACK_READ_OPF_SECTION", "MSK_CALLBACK_IM_LU", "MSK_CALLBACK_IM_ORDER",
    "MSK_CALLBACK_READ_OPF", "MSK_CALLBACK_WRITE_OPF", "MSK_CALLBACK_SOLVING_REMOTE",
    "MSK_CALLBACK_HEARTBEAT", "MSK_COMPRESS_NONE", "MSK_COMPRESS_FREE", "MSK_COMPRESS_GZIP",
    "MSK_COMPRESS_ZSTD", "MSK_CT_QUAD", "MSK_CT_RQUAD", "MSK_CT_PEXP", "MSK_CT_DEXP",
    "MSK_CT_PPOW", "MSK_CT_DPOW", "MSK_CT_ZERO", "MSK_DOMAIN_R", "MSK_DOMAIN_RZERO",
    "MSK_DOMAIN_RPLUS", "MSK_DOMAIN_RMINUS", "MSK_DOMAIN_QUADRATIC_CONE",
    "MSK_DOMAIN_RQUADRATIC_CONE", "MSK_DOMAIN_PRIMAL_EXP_CONE", "MSK_DOMAIN_DUAL_EXP_CONE",
    "MSK_DOMAIN_PRIMAL_POWER_CONE", "MSK_DOMAIN_DUAL_POWER_CONE",
    "MSK_DOMAIN_PRIMAL_GEO_MEAN_CONE", "MSK_DOMAIN_DUAL_GEO_MEAN_CONE",
    "MSK_DOMAIN_SVEC_PSD_CONE", "MSK_NAME_TYPE_GEN", "MSK_NAME_TYPE_MPS", "MSK_NAME_TYPE_LP",
    "MSK_SYMMAT_TYPE_SPARSE", "MSK_DATA_FORMAT_EXTENSION", "MSK_DATA_FORMAT_MPS",
    "MSK_DATA_FORMAT_LP", "MSK_DATA_FORMAT_OP", "MSK_DATA_FORMAT_FREE_MPS",
    "MSK_DATA_FORMAT_TASK", "MSK_DATA_FORMAT_PTF", "MSK_DATA_FORMAT_CB",
    "MSK_DATA_FORMAT_JSON_TASK", "MSK_SOL_FORMAT_EXTENSION", "MSK_SOL_FORMAT_B",
    "MSK_SOL_FORMAT_TASK", "MSK_SOL_FORMAT_JSON_TASK",
    "MSK_DINF_ANA_PRO_SCALARIZED_CONSTRAINT_MATRIX_DENSITY", "MSK_DINF_BI_TIME",
    "MSK_DINF_BI_PRIMAL_TIME", "MSK_DINF_BI_DUAL_TIME", "MSK_DINF_BI_CLEAN_TIME",
    "MSK_DINF_FOLDING_BI_UNFOLD_INITIALIZE_TIME", "MSK_DINF_FOLDING_BI_UNFOLD_PRIMAL_TIME",
    "MSK_DINF_FOLDING_BI_UNFOLD_DUAL_TIME", "MSK_DINF_FOLDING_BI_OPTIMIZE_TIME",
    "MSK_DINF_FOLDING_BI_UNFOLD_TIME", "MSK_DINF_INTPNT_TIME", "MSK_DINF_INTPNT_ORDER_TIME",
    "MSK_DINF_INTPNT_PRIMAL_OBJ", "MSK_DINF_INTPNT_DUAL_OBJ", "MSK_DINF_INTPNT_PRIMAL_FEAS",
    "MSK_DINF_INTPNT_DUAL_FEAS", "MSK_DINF_INTPNT_OPT_STATUS", "MSK_DINF_SIM_TIME",
    "MSK_DINF_SIM_PRIMAL_TIME", "MSK_DINF_SIM_DUAL_TIME", "MSK_DINF_SIM_OBJ",
    "MSK_DINF_SIM_FEAS", "MSK_DINF_MIO_TIME", "MSK_DINF_MIO_ROOT_PRESOLVE_TIME",
    "MSK_DINF_MIO_ROOT_OPTIMIZER_TIME", "MSK_DINF_MIO_ROOT_TIME", "MSK_DINF_TO_CONIC_TIME",
    "MSK_DINF_MIO_CONSTRUCT_SOLUTION_OBJ", "MSK_DINF_MIO_INITIAL_FEASIBLE_SOLUTION_OBJ",
    "MSK_DINF_MIO_OBJ_INT", "MSK_DINF_MIO_OBJ_BOUND", "MSK_DINF_MIO_OBJ_REL_GAP",
    "MSK_DINF_MIO_OBJ_ABS_GAP", "MSK_DINF_MIO_USER_OBJ_CUT",
    "MSK_DINF_MIO_CMIR_SEPARATION_TIME", "MSK_DINF_MIO_CLIQUE_SEPARATION_TIME",
    "MSK_DINF_MIO_KNAPSACK_COVER_SEPARATION_TIME", "MSK_DINF_MIO_GMI_SEPARATION_TIME",
    "MSK_DINF_MIO_IMPLIED_BOUND_SEPARATION_TIME", "MSK_DINF_MIO_LIPRO_SEPARATION_TIME",
    "MSK_DINF_MIO_ROOT_CUT_SEPARATION_TIME", "MSK_DINF_MIO_CMIR_SELECTION_TIME",
    "MSK_DINF_MIO_CLIQUE_SELECTION_TIME", "MSK_DINF_MIO_KNAPSACK_COVER_SELECTION_TIME",
    "MSK_DINF_MIO_GMI_SELECTION_TIME", "MSK_DINF_MIO_IMPLIED_BOUND_SELECTION_TIME",
    "MSK_DINF_MIO_LIPRO_SELECTION_TIME", "MSK_DINF_MIO_ROOT_CUT_SELECTION_TIME",
    "MSK_DINF_MIO_PROBING_TIME", "MSK_DINF_MIO_SYMMETRY_DETECTION_TIME",
    "MSK_DINF_OPTIMIZER_TIME", "MSK_DINF_OPTIMIZER_TICKS", "MSK_DINF_PRESOLVE_TIME",
    "MSK_DINF_MIO_SYMMETRY_FACTOR", "MSK_DINF_MIO_DUAL_BOUND_AFTER_PRESOLVE",
    "MSK_DINF_PRESOLVE_ELI_TIME", "MSK_DINF_PRESOLVE_LINDEP_TIME", "MSK_DINF_FOLDING_TIME",
    "MSK_DINF_FOLDING_FACTOR", "MSK_DINF_READ_DATA_TIME", "MSK_DINF_WRITE_DATA_TIME",
    "MSK_DINF_SOL_ITR_PRIMAL_OBJ", "MSK_DINF_SOL_ITR_PVIOLCON", "MSK_DINF_SOL_ITR_PVIOLVAR",
    "MSK_DINF_SOL_ITR_PVIOLBARVAR", "MSK_DINF_SOL_ITR_PVIOLCONES", "MSK_DINF_SOL_ITR_PVIOLACC",
    "MSK_DINF_SOL_ITR_DUAL_OBJ", "MSK_DINF_SOL_ITR_DVIOLCON", "MSK_DINF_SOL_ITR_DVIOLVAR",
    "MSK_DINF_SOL_ITR_DVIOLBARVAR", "MSK_DINF_SOL_ITR_DVIOLCONES", "MSK_DINF_SOL_ITR_DVIOLACC",
    "MSK_DINF_SOL_ITR_NRM_XC", "MSK_DINF_SOL_ITR_NRM_XX", "MSK_DINF_SOL_ITR_NRM_BARX",
    "MSK_DINF_SOL_ITR_NRM_Y", "MSK_DINF_SOL_ITR_NRM_SLC", "MSK_DINF_SOL_ITR_NRM_SUC",
    "MSK_DINF_SOL_ITR_NRM_SLX", "MSK_DINF_SOL_ITR_NRM_SUX", "MSK_DINF_SOL_ITR_NRM_SNX",
    "MSK_DINF_SOL_ITR_NRM_BARS", "MSK_DINF_SOL_BAS_PRIMAL_OBJ", "MSK_DINF_SOL_BAS_PVIOLCON",
    "MSK_DINF_SOL_BAS_PVIOLVAR", "MSK_DINF_SOL_BAS_DUAL_OBJ", "MSK_DINF_SOL_BAS_DVIOLCON",
    "MSK_DINF_SOL_BAS_DVIOLVAR", "MSK_DINF_SOL_BAS_NRM_XC", "MSK_DINF_SOL_BAS_NRM_XX",
    "MSK_DINF_SOL_BAS_NRM_BARX", "MSK_DINF_SOL_BAS_NRM_Y", "MSK_DINF_SOL_BAS_NRM_SLC",
    "MSK_DINF_SOL_BAS_NRM_SUC", "MSK_DINF_SOL_BAS_NRM_SLX", "MSK_DINF_SOL_BAS_NRM_SUX",
    "MSK_DINF_SOL_ITG_PRIMAL_OBJ", "MSK_DINF_SOL_ITG_PVIOLCON", "MSK_DINF_SOL_ITG_PVIOLVAR",
    "MSK_DINF_SOL_ITG_PVIOLBARVAR", "MSK_DINF_SOL_ITG_PVIOLCONES", "MSK_DINF_SOL_ITG_PVIOLACC",
    "MSK_DINF_SOL_ITG_PVIOLITG", "MSK_DINF_SOL_ITG_PVIOLDJC", "MSK_DINF_SOL_ITG_NRM_XC",
    "MSK_DINF_SOL_ITG_NRM_XX", "MSK_DINF_SOL_ITG_NRM_BARX",
    "MSK_DINF_PRESOLVE_TOTAL_PRIMAL_PERTURBATION", "MSK_DINF_INTPNT_FACTOR_NUM_FLOPS",
    "MSK_DINF_QCQO_REFORMULATE_TIME", "MSK_DINF_QCQO_REFORMULATE_MAX_PERTURBATION",
    "MSK_DINF_QCQO_REFORMULATE_WORST_CHOLESKY_DIAG_SCALING",
    "MSK_DINF_QCQO_REFORMULATE_WORST_CHOLESKY_COLUMN_SCALING",
    "MSK_DINF_PRIMAL_REPAIR_PENALTY_OBJ", "MSK_DINF_REMOTE_TIME", "MSK_FEATURE_PTS",
    "MSK_FEATURE_PTON", "MSK_DPAR_DATA_TOL_CJ_LARGE", "MSK_DPAR_DATA_TOL_C_HUGE",
    "MSK_DPAR_DATA_TOL_AIJ_LARGE", "MSK_DPAR_DATA_TOL_AIJ_HUGE", "MSK_DPAR_DATA_SYM_MAT_TOL",
    "MSK_DPAR_DATA_SYM_MAT_TOL_LARGE", "MSK_DPAR_DATA_SYM_MAT_TOL_HUGE",
    "MSK_DPAR_DATA_TOL_BOUND_INF", "MSK_DPAR_DATA_TOL_BOUND_WRN", "MSK_DPAR_DATA_TOL_QIJ",
    "MSK_DPAR_DATA_TOL_X", "MSK_DPAR_SEMIDEFINITE_TOL_APPROX", "MSK_DPAR_OPTIMIZER_MAX_TIME",
    "MSK_DPAR_OPTIMIZER_MAX_TICKS", "MSK_DPAR_LOWER_OBJ_CUT", "MSK_DPAR_UPPER_OBJ_CUT",
    "MSK_DPAR_UPPER_OBJ_CUT_FINITE_TRH", "MSK_DPAR_LOWER_OBJ_CUT_FINITE_TRH",
    "MSK_DPAR_INTPNT_TOL_REL_GAP", "MSK_DPAR_INTPNT_TOL_STEP_SIZE",
    "MSK_DPAR_SIM_LU_TOL_REL_PIV", "MSK_DPAR_INTPNT_TOL_REL_STEP", "MSK_DPAR_INTPNT_TOL_PATH",
    "MSK_DPAR_INTPNT_TOL_PFEAS", "MSK_DPAR_INTPNT_TOL_DFEAS", "MSK_DPAR_INTPNT_TOL_MU_RED",
    "MSK_DPAR_INTPNT_TOL_INFEAS", "MSK_DPAR_INTPNT_CO_TOL_REL_GAP",
    "MSK_DPAR_INTPNT_CO_TOL_PFEAS", "MSK_DPAR_INTPNT_CO_TOL_DFEAS",
    "MSK_DPAR_INTPNT_CO_TOL_MU_RED", "MSK_DPAR_INTPNT_CO_TOL_NEAR_REL",
    "MSK_DPAR_INTPNT_CO_TOL_INFEAS", "MSK_DPAR_INTPNT_QO_TOL_REL_GAP",
    "MSK_DPAR_INTPNT_QO_TOL_PFEAS", "MSK_DPAR_INTPNT_QO_TOL_DFEAS",
    "MSK_DPAR_INTPNT_QO_TOL_MU_RED", "MSK_DPAR_INTPNT_QO_TOL_NEAR_REL",
    "MSK_DPAR_INTPNT_QO_TOL_INFEAS", "MSK_DPAR_INTPNT_TOL_PSAFE", "MSK_DPAR_INTPNT_TOL_DSAFE",
    "MSK_DPAR_MIO_MAX_TIME", "MSK_DPAR_MIO_REL_GAP_CONST", "MSK_DPAR_MIO_TOL_REL_GAP",
    "MSK_DPAR_MIO_TOL_ABS_GAP", "MSK_DPAR_MIO_TOL_ABS_RELAX_INT", "MSK_DPAR_MIO_DJC_MAX_BIGM",
    "MSK_DPAR_MIO_CLIQUE_TABLE_SIZE_FACTOR", "MSK_DPAR_SIM_PRECISION_SCALING_NORMAL",
    "MSK_DPAR_SIM_PRECISION_SCALING_EXTENDED", "MSK_DPAR_BASIS_TOL_X", "MSK_DPAR_BASIS_TOL_S",
    "MSK_DPAR_BASIS_REL_TOL_S", "MSK_DPAR_PRESOLVE_TOL_X",
    "MSK_DPAR_PRESOLVE_TOL_PRIMAL_INFEAS_PERTURBATION", "MSK_DPAR_PRESOLVE_TOL_S",
    "MSK_DPAR_PRESOLVE_TOL_ABS_LINDEP", "MSK_DPAR_PRESOLVE_TOL_REL_LINDEP",
    "MSK_DPAR_FOLDING_TOL_EQ", "MSK_DPAR_SIMPLEX_ABS_TOL_PIV", "MSK_DPAR_MIO_TOL_FEAS",
    "MSK_DPAR_ANA_SOL_INFEAS_TOL", "MSK_DPAR_QCQO_REFORMULATE_REL_DROP_TOL",
    "MSK_DPAR_MIO_TOL_REL_DUAL_BOUND_IMPROVEMENT",
    "MSK_LIINF_ANA_PRO_SCALARIZED_CONSTRAINT_MATRIX_NUM_ROWS",
    "MSK_LIINF_ANA_PRO_SCALARIZED_CONSTRAINT_MATRIX_NUM_COLUMNS",
    "MSK_LIINF_ANA_PRO_SCALARIZED_CONSTRAINT_MATRIX_NUM_NZ", "MSK_LIINF_MIO_ANZ",
    "MSK_LIINF_MIO_PRESOLVED_ANZ", "MSK_LIINF_MIO_FINAL_ANZ", "MSK_LIINF_MIO_SIMPLEX_ITER",
    "MSK_LIINF_MIO_INTPNT_ITER", "MSK_LIINF_MIO_NUM_PRIM_ILLPOSED_CER",
    "MSK_LIINF_MIO_NUM_DUAL_ILLPOSED_CER", "MSK_LIINF_BI_PRIMAL_ITER",
    "MSK_LIINF_BI_DUAL_ITER", "MSK_LIINF_BI_CLEAN_ITER", "MSK_LIINF_INTPNT_FACTOR_NUM_NZ",
    "MSK_LIINF_FOLDING_BI_PRIMAL_ITER", "MSK_LIINF_FOLDING_BI_DUAL_ITER",
    "MSK_LIINF_FOLDING_BI_OPTIMIZER_ITER", "MSK_LIINF_RD_NUMACC", "MSK_LIINF_RD_NUMDJC",
    "MSK_LIINF_RD_NUMANZ", "MSK_LIINF_RD_NUMQNZ", "MSK_LIINF_SIMPLEX_ITER",
    "MSK_IINF_ANA_PRO_NUM_CON", "MSK_IINF_ANA_PRO_NUM_CON_LO", "MSK_IINF_ANA_PRO_NUM_CON_UP",
    "MSK_IINF_ANA_PRO_NUM_CON_RA", "MSK_IINF_ANA_PRO_NUM_CON_EQ",
    "MSK_IINF_ANA_PRO_NUM_CON_FR", "MSK_IINF_ANA_PRO_NUM_VAR", "MSK_IINF_ANA_PRO_NUM_VAR_LO",
    "MSK_IINF_ANA_PRO_NUM_VAR_UP", "MSK_IINF_ANA_PRO_NUM_VAR_RA",
    "MSK_IINF_ANA_PRO_NUM_VAR_EQ", "MSK_IINF_ANA_PRO_NUM_VAR_FR",
    "MSK_IINF_ANA_PRO_NUM_VAR_CONT", "MSK_IINF_ANA_PRO_NUM_VAR_BIN",
    "MSK_IINF_ANA_PRO_NUM_VAR_INT", "MSK_IINF_OPTIMIZE_RESPONSE",
    "MSK_IINF_PRESOLVE_NUM_PRIMAL_PERTURBATIONS", "MSK_IINF_INTPNT_ITER",
    "MSK_IINF_INTPNT_FACTOR_DIM_DENSE", "MSK_IINF_INTPNT_SOLVE_DUAL",
    "MSK_IINF_MIO_NODE_DEPTH", "MSK_IINF_MIO_NUMVAR", "MSK_IINF_MIO_NUMBIN",
    "MSK_IINF_MIO_NUMINT", "MSK_IINF_MIO_NUMCONT", "MSK_IINF_MIO_NUMCON",
    "MSK_IINF_MIO_NUMCONE", "MSK_IINF_MIO_NUMQCONES", "MSK_IINF_MIO_NUMRQCONES",
    "MSK_IINF_MIO_NUMPEXPCONES", "MSK_IINF_MIO_NUMDEXPCONES", "MSK_IINF_MIO_NUMPPOWCONES",
    "MSK_IINF_MIO_NUMDPOWCONES", "MSK_IINF_MIO_NUMCONEVAR", "MSK_IINF_MIO_NUMBINCONEVAR",
    "MSK_IINF_MIO_NUMINTCONEVAR", "MSK_IINF_MIO_NUMCONTCONEVAR", "MSK_IINF_MIO_NUMDJC",
    "MSK_IINF_MIO_PRESOLVED_NUMVAR", "MSK_IINF_MIO_PRESOLVED_NUMBIN",
    "MSK_IINF_MIO_PRESOLVED_NUMINT", "MSK_IINF_MIO_PRESOLVED_NUMCONT",
    "MSK_IINF_MIO_PRESOLVED_NUMCON", "MSK_IINF_MIO_PRESOLVED_NUMCONE",
    "MSK_IINF_MIO_PRESOLVED_NUMQCONES", "MSK_IINF_MIO_PRESOLVED_NUMRQCONES",
    "MSK_IINF_MIO_PRESOLVED_NUMPEXPCONES", "MSK_IINF_MIO_PRESOLVED_NUMDEXPCONES",
    "MSK_IINF_MIO_PRESOLVED_NUMPPOWCONES", "MSK_IINF_MIO_PRESOLVED_NUMDPOWCONES",
    "MSK_IINF_MIO_PRESOLVED_NUMCONEVAR", "MSK_IINF_MIO_PRESOLVED_NUMBINCONEVAR",
    "MSK_IINF_MIO_PRESOLVED_NUMINTCONEVAR", "MSK_IINF_MIO_PRESOLVED_NUMCONTCONEVAR",
    "MSK_IINF_MIO_PRESOLVED_NUMDJC", "MSK_IINF_MIO_FINAL_NUMVAR", "MSK_IINF_MIO_FINAL_NUMBIN",
    "MSK_IINF_MIO_FINAL_NUMINT", "MSK_IINF_MIO_FINAL_NUMCONT", "MSK_IINF_MIO_FINAL_NUMCON",
    "MSK_IINF_MIO_FINAL_NUMCONE", "MSK_IINF_MIO_FINAL_NUMQCONES",
    "MSK_IINF_MIO_FINAL_NUMRQCONES", "MSK_IINF_MIO_FINAL_NUMPEXPCONES",
    "MSK_IINF_MIO_FINAL_NUMDEXPCONES", "MSK_IINF_MIO_FINAL_NUMPPOWCONES",
    "MSK_IINF_MIO_FINAL_NUMDPOWCONES", "MSK_IINF_MIO_FINAL_NUMCONEVAR",
    "MSK_IINF_MIO_FINAL_NUMBINCONEVAR", "MSK_IINF_MIO_FINAL_NUMINTCONEVAR",
    "MSK_IINF_MIO_FINAL_NUMCONTCONEVAR", "MSK_IINF_MIO_FINAL_NUMDJC",
    "MSK_IINF_MIO_CLIQUE_TABLE_SIZE", "MSK_IINF_MIO_CONSTRUCT_SOLUTION",
    "MSK_IINF_MIO_INITIAL_FEASIBLE_SOLUTION", "MSK_IINF_MIO_NUM_INT_SOLUTIONS",
    "MSK_IINF_MIO_OBJ_BOUND_DEFINED", "MSK_IINF_MIO_NUM_ACTIVE_NODES",
    "MSK_IINF_MIO_NUM_RELAX", "MSK_IINF_MIO_NUM_SOLVED_NODES", "MSK_IINF_MIO_NUM_BRANCH",
    "MSK_IINF_MIO_NUM_RESTARTS", "MSK_IINF_MIO_NUM_ROOT_CUT_ROUNDS",
    "MSK_IINF_MIO_NUM_ACTIVE_ROOT_CUTS", "MSK_IINF_MIO_TOTAL_NUM_SELECTED_CUTS",
    "MSK_IINF_MIO_NUM_SELECTED_CMIR_CUTS", "MSK_IINF_MIO_NUM_SELECTED_CLIQUE_CUTS",
    "MSK_IINF_MIO_NUM_SELECTED_IMPLIED_BOUND_CUTS",
    "MSK_IINF_MIO_NUM_SELECTED_KNAPSACK_COVER_CUTS", "MSK_IINF_MIO_NUM_SELECTED_GOMORY_CUTS",
    "MSK_IINF_MIO_NUM_SELECTED_LIPRO_CUTS", "MSK_IINF_MIO_TOTAL_NUM_SEPARATED_CUTS",
    "MSK_IINF_MIO_NUM_SEPARATED_CMIR_CUTS", "MSK_IINF_MIO_NUM_SEPARATED_CLIQUE_CUTS",
    "MSK_IINF_MIO_NUM_SEPARATED_IMPLIED_BOUND_CUTS",
    "MSK_IINF_MIO_NUM_SEPARATED_KNAPSACK_COVER_CUTS", "MSK_IINF_MIO_NUM_SEPARATED_GOMORY_CUTS",
    "MSK_IINF_MIO_NUM_SEPARATED_LIPRO_CUTS", "MSK_IINF_MIO_NUM_REPEATED_PRESOLVE",
    "MSK_IINF_MIO_NUM_BLOCKS_SOLVED_IN_PRESOLVE", "MSK_IINF_MIO_NUM_BLOCKS_SOLVED_IN_BB",
    "MSK_IINF_MIO_USER_OBJ_CUT", "MSK_IINF_MIO_RELGAP_SATISFIED",
    "MSK_IINF_MIO_ABSGAP_SATISFIED", "MSK_IINF_FOLDING_APPLIED", "MSK_IINF_RD_PROTYPE",
    "MSK_IINF_RD_NUMCON", "MSK_IINF_RD_NUMVAR", "MSK_IINF_RD_NUMBARVAR",
    "MSK_IINF_RD_NUMINTVAR", "MSK_IINF_RD_NUMQ", "MSK_IINF_SIM_DUAL_DEG_ITER",
    "MSK_IINF_SIM_DUAL_INF_ITER", "MSK_IINF_SIM_DUAL_HOTSTART_LU", "MSK_IINF_SIM_PRIMAL_ITER",
    "MSK_IINF_SIM_DUAL_ITER", "MSK_IINF_INTPNT_NUM_THREADS", "MSK_IINF_SIM_PRIMAL_INF_ITER",
    "MSK_IINF_SIM_PRIMAL_DEG_ITER", "MSK_IINF_SIM_PRIMAL_HOTSTART",
    "MSK_IINF_SIM_PRIMAL_HOTSTART_LU", "MSK_IINF_SIM_DUAL_HOTSTART", "MSK_IINF_SOL_ITR_PROSTA",
    "MSK_IINF_SOL_ITR_SOLSTA", "MSK_IINF_SOL_BAS_PROSTA", "MSK_IINF_SOL_BAS_SOLSTA",
    "MSK_IINF_SOL_ITG_PROSTA", "MSK_IINF_SOL_ITG_SOLSTA", "MSK_IINF_SIM_NUMCON",
    "MSK_IINF_SIM_NUMVAR", "MSK_IINF_OPT_NUMCON", "MSK_IINF_OPT_NUMVAR",
    "MSK_IINF_STO_NUM_A_REALLOC", "MSK_IINF_RD_NUMCONE", "MSK_IINF_SIM_SOLVE_DUAL",
    "MSK_IINF_PURIFY_PRIMAL_SUCCESS", "MSK_IINF_PURIFY_DUAL_SUCCESS", "MSK_INF_DOU_TYPE",
    "MSK_INF_INT_TYPE", "MSK_INF_LINT_TYPE", "MSK_IOMODE_READ", "MSK_IOMODE_WRITE",
    "MSK_IOMODE_READWRITE", "MSK_IPAR_AUTO_UPDATE_SOL_INFO",
    "MSK_IPAR_REMOVE_UNUSED_SOLUTIONS", "MSK_IPAR_INTPNT_HOTSTART", "MSK_IPAR_NUM_THREADS",
    "MSK_IPAR_TIMING_LEVEL", "MSK_IPAR_MT_SPINCOUNT", "MSK_IPAR_MAX_NUM_WARNINGS",
    "MSK_IPAR_OPTIMIZER", "MSK_IPAR_SIM_PRECISION", "MSK_IPAR_BI_MAX_ITERATIONS",
    "MSK_IPAR_LICENSE_TRH_EXPIRY_WRN", "MSK_IPAR_LOG_INCLUDE_SUMMARY",
    "MSK_IPAR_LOG_CUT_SECOND_OPT", "MSK_IPAR_LOG_ANA_PRO", "MSK_IPAR_LOG_LOCAL_INFO",
    "MSK_IPAR_LOG_BI", "MSK_IPAR_LOG_BI_FREQ", "MSK_IPAR_BI_CLEAN_OPTIMIZER",
    "MSK_IPAR_INTPNT_STARTING_POINT", "MSK_IPAR_INTPNT_DIFF_STEP", "MSK_IPAR_INTPNT_SCALING",
    "MSK_IPAR_INTPNT_SOLVE_FORM", "MSK_IPAR_LOG_INTPNT", "MSK_IPAR_INTPNT_MAX_ITERATIONS",
    "MSK_IPAR_INTPNT_OFF_COL_TRH", "MSK_IPAR_INTPNT_ORDER_METHOD",
    "MSK_IPAR_INTPNT_ORDER_GP_NUM_SEEDS", "MSK_IPAR_INTPNT_BASIS",
    "MSK_IPAR_BI_IGNORE_MAX_ITER", "MSK_IPAR_BI_IGNORE_NUM_ERROR",
    "MSK_IPAR_INTPNT_MAX_NUM_COR", "MSK_IPAR_PRESOLVE_USE", "MSK_IPAR_LOG_PRESOLVE",
    "MSK_IPAR_PRESOLVE_LINDEP_USE", "MSK_IPAR_PRESOLVE_LINDEP_NEW",
    "MSK_IPAR_PRESOLVE_MAX_NUM_PASS", "MSK_IPAR_PRESOLVE_ELIMINATOR_MAX_NUM_TRIES",
    "MSK_IPAR_PRESOLVE_ELIMINATOR_MAX_FILL", "MSK_IPAR_PRESOLVE_MAX_NUM_REDUCTIONS",
    "MSK_IPAR_FOLDING_USE", "MSK_IPAR_SIM_DETECT_PWL", "MSK_IPAR_SIM_PRIMAL_CRASH",
    "MSK_IPAR_LOG_SIM", "MSK_IPAR_LOG_SIM_FREQ", "MSK_IPAR_LOG_SIM_FREQ_GIGA_TICKS",
    "MSK_IPAR_HEARTBEAT_SIM_FREQ_TICKS", "MSK_IPAR_SIM_PRIMAL_RESTRICT_SELECTION",
    "MSK_IPAR_SIM_PRIMAL_SELECTION", "MSK_IPAR_SIM_DUAL_RESTRICT_SELECTION",
    "MSK_IPAR_SIM_DUAL_SELECTION", "MSK_IPAR_SIM_MAX_ITERATIONS", "MSK_IPAR_SIM_HOTSTART_LU",
    "MSK_IPAR_SIM_REFACTOR_FREQ", "MSK_IPAR_SIM_SEED", "MSK_IPAR_MIO_MODE", "MSK_IPAR_LOG_MIO",
    "MSK_IPAR_LOG_MIO_FREQ", "MSK_IPAR_MIO_MAX_NUM_RELAXS", "MSK_IPAR_MIO_MAX_NUM_BRANCHES",
    "MSK_IPAR_MIO_MAX_NUM_RESTARTS", "MSK_IPAR_MIO_MAX_NUM_ROOT_CUT_ROUNDS",
    "MSK_IPAR_MIO_MAX_NUM_SOLUTIONS", "MSK_IPAR_MIO_NODE_SELECTION",
    "MSK_IPAR_MIO_VAR_SELECTION", "MSK_IPAR_MIO_MIN_REL", "MSK_IPAR_MIO_HEURISTIC_LEVEL",
    "MSK_IPAR_MIO_PROBING_LEVEL", "MSK_IPAR_MIO_SYMMETRY_LEVEL",
    "MSK_IPAR_MIO_DUAL_RAY_ANALYSIS_LEVEL", "MSK_IPAR_MIO_CONFLICT_ANALYSIS_LEVEL",
    "MSK_IPAR_MIO_PRESOLVE_AGGREGATOR_USE", "MSK_IPAR_MIO_NUMERICAL_EMPHASIS_LEVEL",
    "MSK_IPAR_MIO_MEMORY_EMPHASIS_LEVEL", "MSK_IPAR_MIO_CUT_SELECTION_LEVEL",
    "MSK_IPAR_MIO_VB_DETECTION_LEVEL", "MSK_IPAR_MIO_BRANCH_DIR",
    "MSK_IPAR_MIO_ROOT_OPTIMIZER", "MSK_IPAR_MIO_NODE_OPTIMIZER",
    "MSK_IPAR_MIO_PERSPECTIVE_REFORMULATE", "MSK_IPAR_MIO_PROPAGATE_OBJECTIVE_CONSTRAINT",
    "MSK_IPAR_MIO_SEED", "MSK_IPAR_MIO_CONIC_OUTER_APPROXIMATION",
    "MSK_IPAR_MIO_QCQO_REFORMULATION_METHOD", "MSK_IPAR_MIO_DATA_PERMUTATION_METHOD",
    "MSK_IPAR_READ_ASYNC", "MSK_IPAR_WRITE_ASYNC", "MSK_IPAR_READ_KEEP_FREE_CON",
    "MSK_IPAR_READ_MPS_FORMAT", "MSK_IPAR_WRITE_MPS_FORMAT", "MSK_IPAR_READ_MPS_WIDTH",
    "MSK_IPAR_READ_DEBUG", "MSK_IPAR_WRITE_FREE_CON", "MSK_IPAR_WRITE_GENERIC_NAMES",
    "MSK_IPAR_WRITE_COMPRESSION", "MSK_IPAR_WRITE_MPS_INT", "MSK_IPAR_WRITE_LP_LINE_WIDTH",
    "MSK_IPAR_WRITE_LP_FULL_OBJ", "MSK_IPAR_WRITE_JSON_INDENTATION",
    "MSK_IPAR_WRITE_SOL_IGNORE_INVALID_NAMES", "MSK_IPAR_WRITE_SOL_HEAD",
    "MSK_IPAR_WRITE_SOL_CONSTRAINTS", "MSK_IPAR_WRITE_SOL_VARIABLES",
    "MSK_IPAR_WRITE_SOL_BARVARIABLES", "MSK_IPAR_WRITE_BAS_HEAD",
    "MSK_IPAR_WRITE_BAS_CONSTRAINTS", "MSK_IPAR_WRITE_BAS_VARIABLES",
    "MSK_IPAR_WRITE_INT_HEAD", "MSK_IPAR_WRITE_INT_CONSTRAINTS",
    "MSK_IPAR_WRITE_INT_VARIABLES", "MSK_IPAR_SOL_READ_NAME_WIDTH", "MSK_IPAR_SOL_READ_WIDTH",
    "MSK_IPAR_INFEAS_REPORT_AUTO", "MSK_IPAR_INFEAS_REPORT_LEVEL",
    "MSK_IPAR_INFEAS_GENERIC_NAMES", "MSK_IPAR_LOG_INFEAS_ANA", "MSK_IPAR_LICENSE_WAIT",
    "MSK_IPAR_LICENSE_SUPPRESS_EXPIRE_WRNS", "MSK_IPAR_LICENSE_PAUSE_TIME",
    "MSK_IPAR_LICENSE_DEBUG", "MSK_IPAR_SOL_FILTER_KEEP_BASIC", "MSK_IPAR_LOG",
    "MSK_IPAR_LOG_EXPAND", "MSK_IPAR_LOG_FILE", "MSK_IPAR_LOG_ORDER",
    "MSK_IPAR_LOG_SENSITIVITY", "MSK_IPAR_LOG_SENSITIVITY_OPT",
    "MSK_IPAR_READ_TASK_IGNORE_PARAM", "MSK_IPAR_PARAM_READ_CASE_NAME",
    "MSK_IPAR_PARAM_READ_IGN_ERROR", "MSK_IPAR_SIM_SCALING", "MSK_IPAR_SIM_SCALING_METHOD",
    "MSK_IPAR_SIM_PRIMAL_PHASEONE_METHOD", "MSK_IPAR_SIM_DUAL_PHASEONE_METHOD",
    "MSK_IPAR_SIM_MAX_NUM_SETBACKS", "MSK_IPAR_SIM_HOTSTART", "MSK_IPAR_SIM_BASIS_FACTOR_USE",
    "MSK_IPAR_SIM_PRECISION_BOOST", "MSK_IPAR_SIM_DEGEN", "MSK_IPAR_SIM_REFORMULATION",
    "MSK_IPAR_SIM_EXPLOIT_DUPVEC", "MSK_IPAR_SIM_SAVE_LU", "MSK_IPAR_SIM_NON_SINGULAR",
    "MSK_IPAR_SIM_DUAL_CRASH", "MSK_IPAR_LOG_STORAGE", "MSK_IPAR_OPF_WRITE_LINE_LENGTH",
    "MSK_IPAR_OPF_WRITE_HINTS", "MSK_IPAR_OPF_WRITE_PARAMETERS", "MSK_IPAR_OPF_WRITE_PROBLEM",
    "MSK_IPAR_OPF_WRITE_HEADER", "MSK_IPAR_OPF_WRITE_SOLUTIONS", "MSK_IPAR_OPF_WRITE_SOL_BAS",
    "MSK_IPAR_OPF_WRITE_SOL_ITG", "MSK_IPAR_OPF_WRITE_SOL_ITR", "MSK_IPAR_PTF_WRITE_TRANSFORM",
    "MSK_IPAR_PTF_WRITE_SOLUTIONS", "MSK_IPAR_PTF_WRITE_PARAMETERS",
    "MSK_IPAR_PTF_WRITE_SINGLE_PSD_TERMS", "MSK_IPAR_PRIMAL_REPAIR_OPTIMIZER",
    "MSK_IPAR_MIO_CUT_CMIR", "MSK_IPAR_MIO_CUT_CLIQUE", "MSK_IPAR_MIO_CUT_IMPLIED_BOUND",
    "MSK_IPAR_MIO_CUT_KNAPSACK_COVER", "MSK_IPAR_MIO_CUT_GMI", "MSK_IPAR_MIO_CUT_LIPRO",
    "MSK_IPAR_SENSITIVITY_TYPE", "MSK_IPAR_MIO_CONSTRUCT_SOL",
    "MSK_IPAR_PRESOLVE_LINDEP_REL_WORK_TRH", "MSK_IPAR_PRESOLVE_LINDEP_ABS_WORK_TRH",
    "MSK_IPAR_SENSITIVITY_ALL", "MSK_IPAR_LOG_FEAS_REPAIR", "MSK_IPAR_CACHE_LICENSE",
    "MSK_IPAR_INTPNT_REGULARIZATION_USE", "MSK_IPAR_SIM_SOLVE_FORM",
    "MSK_IPAR_SIM_SWITCH_OPTIMIZER", "MSK_IPAR_WRITE_IGNORE_INCOMPATIBLE_ITEMS",
    "MSK_IPAR_AUTO_SORT_A_BEFORE_OPT", "MSK_IPAR_ANA_SOL_BASIS",
    "MSK_IPAR_ANA_SOL_PRINT_VIOLATED", "MSK_IPAR_BASIS_SOLVE_USE_PLUS_ONE",
    "MSK_IPAR_COMPRESS_STATFILE", "MSK_IPAR_MIO_RINS_MAX_NODES", "MSK_IPAR_MIO_RENS_MAX_NODES",
    "MSK_IPAR_MIO_CROSSOVER_MAX_NODES", "MSK_IPAR_MIO_OPT_FACE_MAX_NODES",
    "MSK_IPAR_MIO_FEASPUMP_LEVEL", "MSK_IPAR_MIO_INDEPENDENT_BLOCK_LEVEL", "MSK_IPAR_NG",
    "MSK_IPAR_REMOTE_USE_COMPRESSION", "MSK_IPAR_GETDUAL_CONVERT_LMIS", "MSK_BRANCH_DIR_FREE",
    "MSK_BRANCH_DIR_UP", "MSK_BRANCH_DIR_DOWN", "MSK_BRANCH_DIR_NEAR", "MSK_BRANCH_DIR_FAR",
    "MSK_BRANCH_DIR_ROOT_LP", "MSK_BRANCH_DIR_GUIDED", "MSK_BRANCH_DIR_PSEUDOCOST",
    "MSK_MIO_QCQO_REFORMULATION_METHOD_FREE", "MSK_MIO_QCQO_REFORMULATION_METHOD_NONE",
    "MSK_MIO_QCQO_REFORMULATION_METHOD_LINEARIZATION",
    "MSK_MIO_QCQO_REFORMULATION_METHOD_EIGEN_VAL_METHOD",
    "MSK_MIO_QCQO_REFORMULATION_METHOD_DIAG_SDP",
    "MSK_MIO_QCQO_REFORMULATION_METHOD_RELAX_SDP", "MSK_MIO_DATA_PERMUTATION_METHOD_NONE",
    "MSK_MIO_DATA_PERMUTATION_METHOD_CYCLIC_SHIFT", "MSK_MIO_DATA_PERMUTATION_METHOD_RANDOM",
    "MSK_MIO_CONT_SOL_NONE", "MSK_MIO_CONT_SOL_ROOT", "MSK_MIO_CONT_SOL_ITG",
    "MSK_MIO_CONT_SOL_ITG_REL", "MSK_MIO_MODE_IGNORED", "MSK_MIO_MODE_SATISFIED",
    "MSK_MIO_NODE_SELECTION_FREE", "MSK_MIO_NODE_SELECTION_FIRST",
    "MSK_MIO_NODE_SELECTION_BEST", "MSK_MIO_NODE_SELECTION_PSEUDO",
    "MSK_MIO_VAR_SELECTION_FREE", "MSK_MIO_VAR_SELECTION_PSEUDOCOST",
    "MSK_MIO_VAR_SELECTION_STRONG", "MSK_MPS_FORMAT_STRICT", "MSK_MPS_FORMAT_RELAXED",
    "MSK_MPS_FORMAT_FREE", "MSK_MPS_FORMAT_CPLEX", "MSK_OBJECTIVE_SENSE_MINIMIZE",
    "MSK_OBJECTIVE_SENSE_MAXIMIZE", "MSK_ON", "MSK_OFF", "MSK_OPTIMIZER_FREE",
    "MSK_OPTIMIZER_INTPNT", "MSK_OPTIMIZER_CONIC", "MSK_OPTIMIZER_PRIMAL_SIMPLEX",
    "MSK_OPTIMIZER_DUAL_SIMPLEX", "MSK_OPTIMIZER_NEW_PRIMAL_SIMPLEX",
    "MSK_OPTIMIZER_NEW_DUAL_SIMPLEX", "MSK_OPTIMIZER_FREE_SIMPLEX", "MSK_OPTIMIZER_MIXED_INT",
    "MSK_ORDER_METHOD_FREE", "MSK_ORDER_METHOD_APPMINLOC", "MSK_ORDER_METHOD_EXPERIMENTAL",
    "MSK_ORDER_METHOD_TRY_GRAPHPAR", "MSK_ORDER_METHOD_FORCE_GRAPHPAR",
    "MSK_ORDER_METHOD_NONE", "MSK_PRESOLVE_MODE_OFF", "MSK_PRESOLVE_MODE_ON",
    "MSK_PRESOLVE_MODE_FREE", "MSK_FOLDING_MODE_OFF", "MSK_FOLDING_MODE_FREE",
    "MSK_FOLDING_MODE_FREE_UNLESS_BASIC", "MSK_FOLDING_MODE_FORCE", "MSK_PAR_INVALID_TYPE",
    "MSK_PAR_DOU_TYPE", "MSK_PAR_INT_TYPE", "MSK_PAR_STR_TYPE", "MSK_PI_VAR", "MSK_PI_CON",
    "MSK_PI_CONE", "MSK_PROBTYPE_LO", "MSK_PROBTYPE_QO", "MSK_PROBTYPE_QCQO",
    "MSK_PROBTYPE_CONIC", "MSK_PROBTYPE_MIXED", "MSK_PRO_STA_UNKNOWN",
    "MSK_PRO_STA_PRIM_AND_DUAL_FEAS", "MSK_PRO_STA_PRIM_FEAS", "MSK_PRO_STA_DUAL_FEAS",
    "MSK_PRO_STA_PRIM_INFEAS", "MSK_PRO_STA_DUAL_INFEAS", "MSK_PRO_STA_PRIM_AND_DUAL_INFEAS",
    "MSK_PRO_STA_ILL_POSED", "MSK_PRO_STA_PRIM_INFEAS_OR_UNBOUNDED", "MSK_RES_OK",
    "MSK_RES_WRN_OPEN_PARAM_FILE", "MSK_RES_WRN_LARGE_BOUND", "MSK_RES_WRN_LARGE_LO_BOUND",
    "MSK_RES_WRN_LARGE_UP_BOUND", "MSK_RES_WRN_LARGE_CON_FX", "MSK_RES_WRN_LARGE_CJ",
    "MSK_RES_WRN_LARGE_AIJ", "MSK_RES_WRN_ZERO_AIJ", "MSK_RES_WRN_NAME_MAX_LEN",
    "MSK_RES_WRN_SPAR_MAX_LEN", "MSK_RES_WRN_MPS_SPLIT_RHS_VECTOR",
    "MSK_RES_WRN_MPS_SPLIT_RAN_VECTOR", "MSK_RES_WRN_MPS_SPLIT_BOU_VECTOR",
    "MSK_RES_WRN_LP_OLD_QUAD_FORMAT", "MSK_RES_WRN_LP_DROP_VARIABLE",
    "MSK_RES_WRN_NZ_IN_UPR_TRI", "MSK_RES_WRN_DROPPED_NZ_QOBJ", "MSK_RES_WRN_IGNORE_INTEGER",
    "MSK_RES_WRN_NO_GLOBAL_OPTIMIZER", "MSK_RES_WRN_MIO_INFEASIBLE_FINAL",
    "MSK_RES_WRN_SOL_FILTER", "MSK_RES_WRN_UNDEF_SOL_FILE_NAME",
    "MSK_RES_WRN_SOL_FILE_IGNORED_CON", "MSK_RES_WRN_SOL_FILE_IGNORED_VAR",
    "MSK_RES_WRN_TOO_FEW_BASIS_VARS", "MSK_RES_WRN_TOO_MANY_BASIS_VARS",
    "MSK_RES_WRN_LICENSE_EXPIRE", "MSK_RES_WRN_LICENSE_SERVER", "MSK_RES_WRN_EMPTY_NAME",
    "MSK_RES_WRN_USING_GENERIC_NAMES", "MSK_RES_WRN_INVALID_MPS_NAME",
    "MSK_RES_WRN_INVALID_MPS_OBJ_NAME", "MSK_RES_WRN_LICENSE_FEATURE_EXPIRE",
    "MSK_RES_WRN_PARAM_NAME_DOU", "MSK_RES_WRN_PARAM_NAME_INT", "MSK_RES_WRN_PARAM_NAME_STR",
    "MSK_RES_WRN_PARAM_STR_VALUE", "MSK_RES_WRN_PARAM_IGNORED_CMIO",
    "MSK_RES_WRN_ZEROS_IN_SPARSE_ROW", "MSK_RES_WRN_ZEROS_IN_SPARSE_COL",
    "MSK_RES_WRN_INCOMPLETE_LINEAR_DEPENDENCY_CHECK", "MSK_RES_WRN_ELIMINATOR_SPACE",
    "MSK_RES_WRN_PRESOLVE_OUTOFSPACE", "MSK_RES_WRN_PRESOLVE_PRIMAL_PERTURBATIONS",
    "MSK_RES_WRN_WRITE_CHANGED_NAMES", "MSK_RES_WRN_WRITE_DISCARDED_CFIX",
    "MSK_RES_WRN_DUPLICATE_CONSTRAINT_NAMES", "MSK_RES_WRN_DUPLICATE_VARIABLE_NAMES",
    "MSK_RES_WRN_DUPLICATE_BARVARIABLE_NAMES", "MSK_RES_WRN_DUPLICATE_CONE_NAMES",
    "MSK_RES_WRN_ANA_LARGE_BOUNDS", "MSK_RES_WRN_ANA_C_ZERO", "MSK_RES_WRN_ANA_EMPTY_COLS",
    "MSK_RES_WRN_ANA_CLOSE_BOUNDS", "MSK_RES_WRN_ANA_ALMOST_INT_BOUNDS",
    "MSK_RES_WRN_NO_INFEASIBILITY_REPORT_WHEN_MATRIX_VARIABLES",
    "MSK_RES_WRN_GETDUAL_IGNORES_INTEGRALITY", "MSK_RES_WRN_NO_DUALIZER",
    "MSK_RES_WRN_SYM_MAT_LARGE", "MSK_RES_WRN_MODIFIED_DOUBLE_PARAMETER",
    "MSK_RES_WRN_LARGE_FIJ", "MSK_RES_WRN_PTF_UNKNOWN_SECTION", "MSK_RES_ERR_LICENSE",
    "MSK_RES_ERR_LICENSE_EXPIRED", "MSK_RES_ERR_LICENSE_VERSION",
    "MSK_RES_ERR_LICENSE_OLD_SERVER_VERSION", "MSK_RES_ERR_SIZE_LICENSE",
    "MSK_RES_ERR_PROB_LICENSE", "MSK_RES_ERR_FILE_LICENSE", "MSK_RES_ERR_MISSING_LICENSE_FILE",
    "MSK_RES_ERR_SIZE_LICENSE_CON", "MSK_RES_ERR_SIZE_LICENSE_VAR",
    "MSK_RES_ERR_SIZE_LICENSE_INTVAR", "MSK_RES_ERR_OPTIMIZER_LICENSE", "MSK_RES_ERR_FLEXLM",
    "MSK_RES_ERR_LICENSE_SERVER", "MSK_RES_ERR_LICENSE_MAX",
    "MSK_RES_ERR_LICENSE_MOSEKLM_DAEMON", "MSK_RES_ERR_LICENSE_FEATURE",
    "MSK_RES_ERR_PLATFORM_NOT_LICENSED", "MSK_RES_ERR_LICENSE_CANNOT_ALLOCATE",
    "MSK_RES_ERR_LICENSE_CANNOT_CONNECT", "MSK_RES_ERR_LICENSE_INVALID_HOSTID",
    "MSK_RES_ERR_LICENSE_SERVER_VERSION", "MSK_RES_ERR_LICENSE_NO_SERVER_SUPPORT",
    "MSK_RES_ERR_LICENSE_NO_SERVER_LINE", "MSK_RES_ERR_OLDER_DLL", "MSK_RES_ERR_NEWER_DLL",
    "MSK_RES_ERR_LINK_FILE_DLL", "MSK_RES_ERR_THREAD_MUTEX_INIT",
    "MSK_RES_ERR_THREAD_MUTEX_LOCK", "MSK_RES_ERR_THREAD_MUTEX_UNLOCK",
    "MSK_RES_ERR_THREAD_CREATE", "MSK_RES_ERR_THREAD_COND_INIT", "MSK_RES_ERR_UNKNOWN",
    "MSK_RES_ERR_SPACE", "MSK_RES_ERR_FILE_OPEN", "MSK_RES_ERR_FILE_READ",
    "MSK_RES_ERR_FILE_WRITE", "MSK_RES_ERR_DATA_FILE_EXT", "MSK_RES_ERR_INVALID_FILE_NAME",
    "MSK_RES_ERR_INVALID_SOL_FILE_NAME", "MSK_RES_ERR_END_OF_FILE", "MSK_RES_ERR_NULL_ENV",
    "MSK_RES_ERR_NULL_TASK", "MSK_RES_ERR_INVALID_STREAM", "MSK_RES_ERR_NO_INIT_ENV",
    "MSK_RES_ERR_INVALID_TASK", "MSK_RES_ERR_NULL_POINTER", "MSK_RES_ERR_LIVING_TASKS",
    "MSK_RES_ERR_READ_GZIP", "MSK_RES_ERR_READ_ZSTD", "MSK_RES_ERR_READ_ASYNC",
    "MSK_RES_ERR_BLANK_NAME", "MSK_RES_ERR_DUP_NAME", "MSK_RES_ERR_FORMAT_STRING",
    "MSK_RES_ERR_SPARSITY_SPECIFICATION", "MSK_RES_ERR_MISMATCHING_DIMENSION",
    "MSK_RES_ERR_INVALID_OBJ_NAME", "MSK_RES_ERR_INVALID_CON_NAME",
    "MSK_RES_ERR_INVALID_VAR_NAME", "MSK_RES_ERR_INVALID_CONE_NAME",
    "MSK_RES_ERR_INVALID_BARVAR_NAME", "MSK_RES_ERR_SPACE_LEAKING",
    "MSK_RES_ERR_SPACE_NO_INFO", "MSK_RES_ERR_DIMENSION_SPECIFICATION",
    "MSK_RES_ERR_AXIS_NAME_SPECIFICATION", "MSK_RES_ERR_READ_PREMATURE_EOF",
    "MSK_RES_ERR_READ_FORMAT", "MSK_RES_ERR_WRITE_LP_INVALID_VAR_NAMES",
    "MSK_RES_ERR_WRITE_LP_DUPLICATE_VAR_NAMES", "MSK_RES_ERR_WRITE_LP_INVALID_CON_NAMES",
    "MSK_RES_ERR_WRITE_LP_DUPLICATE_CON_NAMES", "MSK_RES_ERR_MPS_FILE",
    "MSK_RES_ERR_MPS_INV_FIELD", "MSK_RES_ERR_MPS_INV_MARKER", "MSK_RES_ERR_MPS_NULL_CON_NAME",
    "MSK_RES_ERR_MPS_NULL_VAR_NAME", "MSK_RES_ERR_MPS_UNDEF_CON_NAME",
    "MSK_RES_ERR_MPS_UNDEF_VAR_NAME", "MSK_RES_ERR_MPS_INVALID_CON_KEY",
    "MSK_RES_ERR_MPS_INVALID_BOUND_KEY", "MSK_RES_ERR_MPS_INVALID_SEC_NAME",
    "MSK_RES_ERR_MPS_NO_OBJECTIVE", "MSK_RES_ERR_MPS_SPLITTED_VAR",
    "MSK_RES_ERR_MPS_MUL_CON_NAME", "MSK_RES_ERR_MPS_MUL_QSEC", "MSK_RES_ERR_MPS_MUL_QOBJ",
    "MSK_RES_ERR_MPS_INV_SEC_ORDER", "MSK_RES_ERR_MPS_MUL_CSEC", "MSK_RES_ERR_MPS_CONE_TYPE",
    "MSK_RES_ERR_MPS_CONE_OVERLAP", "MSK_RES_ERR_MPS_CONE_REPEAT",
    "MSK_RES_ERR_MPS_NON_SYMMETRIC_Q", "MSK_RES_ERR_MPS_DUPLICATE_Q_ELEMENT",
    "MSK_RES_ERR_MPS_INVALID_OBJSENSE", "MSK_RES_ERR_MPS_TAB_IN_FIELD2",
    "MSK_RES_ERR_MPS_TAB_IN_FIELD3", "MSK_RES_ERR_MPS_TAB_IN_FIELD5",
    "MSK_RES_ERR_MPS_INVALID_OBJ_NAME", "MSK_RES_ERR_MPS_INVALID_KEY",
    "MSK_RES_ERR_MPS_INVALID_INDICATOR_CONSTRAINT",
    "MSK_RES_ERR_MPS_INVALID_INDICATOR_VARIABLE", "MSK_RES_ERR_MPS_INVALID_INDICATOR_VALUE",
    "MSK_RES_ERR_MPS_INVALID_INDICATOR_QUADRATIC_CONSTRAINT", "MSK_RES_ERR_OPF_SYNTAX",
    "MSK_RES_ERR_OPF_PREMATURE_EOF", "MSK_RES_ERR_OPF_MISMATCHED_TAG",
    "MSK_RES_ERR_OPF_DUPLICATE_BOUND", "MSK_RES_ERR_OPF_DUPLICATE_CONSTRAINT_NAME",
    "MSK_RES_ERR_OPF_INVALID_CONE_TYPE", "MSK_RES_ERR_OPF_INCORRECT_TAG_PARAM",
    "MSK_RES_ERR_OPF_INVALID_TAG", "MSK_RES_ERR_OPF_DUPLICATE_CONE_ENTRY",
    "MSK_RES_ERR_OPF_TOO_LARGE", "MSK_RES_ERR_OPF_DUAL_INTEGER_SOLUTION",
    "MSK_RES_ERR_LP_EMPTY", "MSK_RES_ERR_WRITE_MPS_INVALID_NAME",
    "MSK_RES_ERR_LP_INVALID_VAR_NAME", "MSK_RES_ERR_WRITE_OPF_INVALID_VAR_NAME",
    "MSK_RES_ERR_LP_FILE_FORMAT", "MSK_RES_ERR_LP_EXPECTED_NUMBER",
    "MSK_RES_ERR_READ_LP_MISSING_END_TAG", "MSK_RES_ERR_LP_INDICATOR_VAR",
    "MSK_RES_ERR_LP_EXPECTED_OBJECTIVE", "MSK_RES_ERR_LP_EXPECTED_CONSTRAINT_RELATION",
    "MSK_RES_ERR_LP_AMBIGUOUS_CONSTRAINT_BOUND", "MSK_RES_ERR_LP_DUPLICATE_SECTION",
    "MSK_RES_ERR_READ_LP_DELAYED_ROWS_NOT_SUPPORTED", "MSK_RES_ERR_WRITING_FILE",
    "MSK_RES_ERR_WRITE_ASYNC", "MSK_RES_ERR_INVALID_NAME_IN_SOL_FILE",
    "MSK_RES_ERR_JSON_SYNTAX", "MSK_RES_ERR_JSON_STRING", "MSK_RES_ERR_JSON_NUMBER_OVERFLOW",
    "MSK_RES_ERR_JSON_FORMAT", "MSK_RES_ERR_JSON_DATA", "MSK_RES_ERR_JSON_MISSING_DATA",
    "MSK_RES_ERR_PTF_INCOMPATIBILITY", "MSK_RES_ERR_PTF_UNDEFINED_ITEM",
    "MSK_RES_ERR_PTF_INCONSISTENCY", "MSK_RES_ERR_PTF_FORMAT", "MSK_RES_ERR_ARGUMENT_LENNEQ",
    "MSK_RES_ERR_ARGUMENT_TYPE", "MSK_RES_ERR_NUM_ARGUMENTS", "MSK_RES_ERR_IN_ARGUMENT",
    "MSK_RES_ERR_ARGUMENT_DIMENSION", "MSK_RES_ERR_SHAPE_IS_TOO_LARGE",
    "MSK_RES_ERR_INDEX_IS_TOO_SMALL", "MSK_RES_ERR_INDEX_IS_TOO_LARGE",
    "MSK_RES_ERR_INDEX_IS_NOT_UNIQUE", "MSK_RES_ERR_PARAM_NAME", "MSK_RES_ERR_PARAM_NAME_DOU",
    "MSK_RES_ERR_PARAM_NAME_INT", "MSK_RES_ERR_PARAM_NAME_STR", "MSK_RES_ERR_PARAM_INDEX",
    "MSK_RES_ERR_PARAM_IS_TOO_LARGE", "MSK_RES_ERR_PARAM_IS_TOO_SMALL",
    "MSK_RES_ERR_PARAM_VALUE_STR", "MSK_RES_ERR_PARAM_TYPE", "MSK_RES_ERR_INF_DOU_INDEX",
    "MSK_RES_ERR_INF_INT_INDEX", "MSK_RES_ERR_INDEX_ARR_IS_TOO_SMALL",
    "MSK_RES_ERR_INDEX_ARR_IS_TOO_LARGE", "MSK_RES_ERR_INF_LINT_INDEX",
    "MSK_RES_ERR_ARG_IS_TOO_SMALL", "MSK_RES_ERR_ARG_IS_TOO_LARGE",
    "MSK_RES_ERR_INVALID_WHICHSOL", "MSK_RES_ERR_INF_DOU_NAME", "MSK_RES_ERR_INF_INT_NAME",
    "MSK_RES_ERR_INF_TYPE", "MSK_RES_ERR_INF_LINT_NAME", "MSK_RES_ERR_INDEX",
    "MSK_RES_ERR_WHICHSOL", "MSK_RES_ERR_SOLITEM", "MSK_RES_ERR_WHICHITEM_NOT_ALLOWED",
    "MSK_RES_ERR_MAXNUMCON", "MSK_RES_ERR_MAXNUMVAR", "MSK_RES_ERR_MAXNUMBARVAR",
    "MSK_RES_ERR_MAXNUMQNZ", "MSK_RES_ERR_TOO_SMALL_MAX_NUM_NZ", "MSK_RES_ERR_INVALID_IDX",
    "MSK_RES_ERR_INVALID_MAX_NUM", "MSK_RES_ERR_UNALLOWED_WHICHSOL", "MSK_RES_ERR_NUMCONLIM",
    "MSK_RES_ERR_NUMVARLIM", "MSK_RES_ERR_TOO_SMALL_MAXNUMANZ", "MSK_RES_ERR_INV_APTRE",
    "MSK_RES_ERR_MUL_A_ELEMENT", "MSK_RES_ERR_INV_BK", "MSK_RES_ERR_INV_BKC",
    "MSK_RES_ERR_INV_BKX", "MSK_RES_ERR_INV_VAR_TYPE", "MSK_RES_ERR_SOLVER_PROBTYPE",
    "MSK_RES_ERR_OBJECTIVE_RANGE", "MSK_RES_ERR_INV_RESCODE", "MSK_RES_ERR_INV_IINF",
    "MSK_RES_ERR_INV_LIINF", "MSK_RES_ERR_INV_DINF", "MSK_RES_ERR_BASIS",
    "MSK_RES_ERR_INV_SKC", "MSK_RES_ERR_INV_SKX", "MSK_RES_ERR_INV_SKN",
    "MSK_RES_ERR_INV_SK_STR", "MSK_RES_ERR_INV_SK", "MSK_RES_ERR_INV_CONE_TYPE_STR",
    "MSK_RES_ERR_INV_CONE_TYPE", "MSK_RES_ERR_INVALID_SURPLUS", "MSK_RES_ERR_INV_NAME_ITEM",
    "MSK_RES_ERR_PRO_ITEM", "MSK_RES_ERR_INVALID_FORMAT_TYPE", "MSK_RES_ERR_FIRSTI",
    "MSK_RES_ERR_LASTI", "MSK_RES_ERR_FIRSTJ", "MSK_RES_ERR_LASTJ",
    "MSK_RES_ERR_MAX_LEN_IS_TOO_SMALL", "MSK_RES_ERR_NONLINEAR_EQUALITY",
    "MSK_RES_ERR_NONCONVEX", "MSK_RES_ERR_NONLINEAR_RANGED", "MSK_RES_ERR_CON_Q_NOT_PSD",
    "MSK_RES_ERR_CON_Q_NOT_NSD", "MSK_RES_ERR_OBJ_Q_NOT_PSD", "MSK_RES_ERR_OBJ_Q_NOT_NSD",
    "MSK_RES_ERR_ARGUMENT_PERM_ARRAY", "MSK_RES_ERR_CONE_INDEX", "MSK_RES_ERR_CONE_SIZE",
    "MSK_RES_ERR_CONE_OVERLAP", "MSK_RES_ERR_CONE_REP_VAR", "MSK_RES_ERR_MAXNUMCONE",
    "MSK_RES_ERR_CONE_TYPE", "MSK_RES_ERR_CONE_TYPE_STR", "MSK_RES_ERR_CONE_OVERLAP_APPEND",
    "MSK_RES_ERR_REMOVE_CONE_VARIABLE", "MSK_RES_ERR_APPENDING_TOO_BIG_CONE",
    "MSK_RES_ERR_CONE_PARAMETER", "MSK_RES_ERR_SOL_FILE_INVALID_NUMBER", "MSK_RES_ERR_HUGE_C",
    "MSK_RES_ERR_HUGE_AIJ", "MSK_RES_ERR_DUPLICATE_AIJ", "MSK_RES_ERR_LOWER_BOUND_IS_A_NAN",
    "MSK_RES_ERR_UPPER_BOUND_IS_A_NAN", "MSK_RES_ERR_INFINITE_BOUND",
    "MSK_RES_ERR_INV_QOBJ_SUBI", "MSK_RES_ERR_INV_QOBJ_SUBJ", "MSK_RES_ERR_INV_QOBJ_VAL",
    "MSK_RES_ERR_INV_QCON_SUBK", "MSK_RES_ERR_INV_QCON_SUBI", "MSK_RES_ERR_INV_QCON_SUBJ",
    "MSK_RES_ERR_INV_QCON_VAL", "MSK_RES_ERR_QCON_SUBI_TOO_SMALL",
    "MSK_RES_ERR_QCON_SUBI_TOO_LARGE", "MSK_RES_ERR_QOBJ_UPPER_TRIANGLE",
    "MSK_RES_ERR_QCON_UPPER_TRIANGLE", "MSK_RES_ERR_FIXED_BOUND_VALUES",
    "MSK_RES_ERR_TOO_SMALL_A_TRUNCATION_VALUE", "MSK_RES_ERR_INVALID_OBJECTIVE_SENSE",
    "MSK_RES_ERR_UNDEFINED_OBJECTIVE_SENSE", "MSK_RES_ERR_Y_IS_UNDEFINED",
    "MSK_RES_ERR_NAN_IN_DOUBLE_DATA", "MSK_RES_ERR_INF_IN_DOUBLE_DATA",
    "MSK_RES_ERR_NAN_IN_BLC", "MSK_RES_ERR_NAN_IN_BUC", "MSK_RES_ERR_INVALID_CFIX",
    "MSK_RES_ERR_NAN_IN_C", "MSK_RES_ERR_NAN_IN_BLX", "MSK_RES_ERR_NAN_IN_BUX",
    "MSK_RES_ERR_INVALID_AIJ", "MSK_RES_ERR_INVALID_CJ", "MSK_RES_ERR_SYM_MAT_INVALID",
    "MSK_RES_ERR_SYM_MAT_HUGE", "MSK_RES_ERR_INV_PROBLEM", "MSK_RES_ERR_MIXED_CONIC_AND_NL",
    "MSK_RES_ERR_GLOBAL_INV_CONIC_PROBLEM", "MSK_RES_ERR_INV_OPTIMIZER",
    "MSK_RES_ERR_MIO_NO_OPTIMIZER", "MSK_RES_ERR_NO_OPTIMIZER_VAR_TYPE",
    "MSK_RES_ERR_FINAL_SOLUTION", "MSK_RES_ERR_FIRST", "MSK_RES_ERR_LAST",
    "MSK_RES_ERR_SLICE_SIZE", "MSK_RES_ERR_NEGATIVE_SURPLUS", "MSK_RES_ERR_NEGATIVE_APPEND",
    "MSK_RES_ERR_POSTSOLVE", "MSK_RES_ERR_OVERFLOW", "MSK_RES_ERR_NO_BASIS_SOL",
    "MSK_RES_ERR_BASIS_FACTOR", "MSK_RES_ERR_BASIS_SINGULAR", "MSK_RES_ERR_FACTOR",
    "MSK_RES_ERR_FEASREPAIR_CANNOT_RELAX", "MSK_RES_ERR_FEASREPAIR_SOLVING_RELAXED",
    "MSK_RES_ERR_FEASREPAIR_INCONSISTENT_BOUND", "MSK_RES_ERR_REPAIR_INVALID_PROBLEM",
    "MSK_RES_ERR_REPAIR_OPTIMIZATION_FAILED", "MSK_RES_ERR_NAME_MAX_LEN",
    "MSK_RES_ERR_NAME_IS_NULL", "MSK_RES_ERR_INVALID_COMPRESSION",
    "MSK_RES_ERR_INVALID_IOMODE", "MSK_RES_ERR_NO_PRIMAL_INFEAS_CER",
    "MSK_RES_ERR_NO_DUAL_INFEAS_CER", "MSK_RES_ERR_NO_SOLUTION_IN_CALLBACK",
    "MSK_RES_ERR_INV_MARKI", "MSK_RES_ERR_INV_MARKJ", "MSK_RES_ERR_INV_NUMI",
    "MSK_RES_ERR_INV_NUMJ", "MSK_RES_ERR_TASK_INCOMPATIBLE", "MSK_RES_ERR_TASK_INVALID",
    "MSK_RES_ERR_TASK_WRITE", "MSK_RES_ERR_READ_WRITE", "MSK_RES_ERR_TASK_PREMATURE_EOF",
    "MSK_RES_ERR_LU_MAX_NUM_TRIES", "MSK_RES_ERR_INVALID_UTF8", "MSK_RES_ERR_INVALID_WCHAR",
    "MSK_RES_ERR_NO_DUAL_FOR_ITG_SOL", "MSK_RES_ERR_NO_SNX_FOR_BAS_SOL",
    "MSK_RES_ERR_INTERNAL", "MSK_RES_ERR_API_ARRAY_TOO_SMALL", "MSK_RES_ERR_API_CB_CONNECT",
    "MSK_RES_ERR_API_FATAL_ERROR", "MSK_RES_ERR_API_INTERNAL", "MSK_RES_ERR_SEN_FORMAT",
    "MSK_RES_ERR_SEN_UNDEF_NAME", "MSK_RES_ERR_SEN_INDEX_RANGE",
    "MSK_RES_ERR_SEN_BOUND_INVALID_UP", "MSK_RES_ERR_SEN_BOUND_INVALID_LO",
    "MSK_RES_ERR_SEN_INDEX_INVALID", "MSK_RES_ERR_SEN_INVALID_REGEXP",
    "MSK_RES_ERR_SEN_SOLUTION_STATUS", "MSK_RES_ERR_SEN_NUMERICAL",
    "MSK_RES_ERR_SEN_UNHANDLED_PROBLEM_TYPE", "MSK_RES_ERR_UNB_STEP_SIZE",
    "MSK_RES_ERR_IDENTICAL_TASKS", "MSK_RES_ERR_AD_INVALID_CODELIST",
    "MSK_RES_ERR_INTERNAL_TEST_FAILED", "MSK_RES_ERR_INT64_TO_INT32_CAST",
    "MSK_RES_ERR_INFEAS_UNDEFINED", "MSK_RES_ERR_NO_BARX_FOR_SOLUTION",
    "MSK_RES_ERR_NO_BARS_FOR_SOLUTION", "MSK_RES_ERR_BAR_VAR_DIM",
    "MSK_RES_ERR_SYM_MAT_INVALID_ROW_INDEX", "MSK_RES_ERR_SYM_MAT_INVALID_COL_INDEX",
    "MSK_RES_ERR_SYM_MAT_NOT_LOWER_TRINGULAR", "MSK_RES_ERR_SYM_MAT_INVALID_VALUE",
    "MSK_RES_ERR_SYM_MAT_DUPLICATE", "MSK_RES_ERR_INVALID_SYM_MAT_DIM",
    "MSK_RES_ERR_INVALID_FILE_FORMAT_FOR_SYM_MAT", "MSK_RES_ERR_INVALID_FILE_FORMAT_FOR_CFIX",
    "MSK_RES_ERR_INVALID_FILE_FORMAT_FOR_RANGED_CONSTRAINTS",
    "MSK_RES_ERR_INVALID_FILE_FORMAT_FOR_FREE_CONSTRAINTS",
    "MSK_RES_ERR_INVALID_FILE_FORMAT_FOR_CONES",
    "MSK_RES_ERR_INVALID_FILE_FORMAT_FOR_QUADRATIC_TERMS",
    "MSK_RES_ERR_INVALID_FILE_FORMAT_FOR_NONLINEAR",
    "MSK_RES_ERR_INVALID_FILE_FORMAT_FOR_DISJUNCTIVE_CONSTRAINTS",
    "MSK_RES_ERR_INVALID_FILE_FORMAT_FOR_AFFINE_CONIC_CONSTRAINTS",
    "MSK_RES_ERR_DUPLICATE_CONSTRAINT_NAMES", "MSK_RES_ERR_DUPLICATE_VARIABLE_NAMES",
    "MSK_RES_ERR_DUPLICATE_BARVARIABLE_NAMES", "MSK_RES_ERR_DUPLICATE_CONE_NAMES",
    "MSK_RES_ERR_DUPLICATE_DOMAIN_NAMES", "MSK_RES_ERR_DUPLICATE_DJC_NAMES",
    "MSK_RES_ERR_NON_UNIQUE_ARRAY", "MSK_RES_ERR_ARGUMENT_IS_TOO_SMALL",
    "MSK_RES_ERR_ARGUMENT_IS_TOO_LARGE", "MSK_RES_ERR_MIO_INTERNAL",
    "MSK_RES_ERR_INVALID_PROBLEM_TYPE", "MSK_RES_ERR_UNHANDLED_SOLUTION_STATUS",
    "MSK_RES_ERR_UPPER_TRIANGLE", "MSK_RES_ERR_LAU_SINGULAR_MATRIX",
    "MSK_RES_ERR_LAU_NOT_POSITIVE_DEFINITE", "MSK_RES_ERR_LAU_INVALID_LOWER_TRIANGULAR_MATRIX",
    "MSK_RES_ERR_LAU_UNKNOWN", "MSK_RES_ERR_LAU_ARG_M", "MSK_RES_ERR_LAU_ARG_N",
    "MSK_RES_ERR_LAU_ARG_K", "MSK_RES_ERR_LAU_ARG_TRANSA", "MSK_RES_ERR_LAU_ARG_TRANSB",
    "MSK_RES_ERR_LAU_ARG_UPLO", "MSK_RES_ERR_LAU_ARG_TRANS",
    "MSK_RES_ERR_LAU_INVALID_SPARSE_SYMMETRIC_MATRIX", "MSK_RES_ERR_CBF_PARSE",
    "MSK_RES_ERR_CBF_OBJ_SENSE", "MSK_RES_ERR_CBF_NO_VARIABLES",
    "MSK_RES_ERR_CBF_TOO_MANY_CONSTRAINTS", "MSK_RES_ERR_CBF_TOO_MANY_VARIABLES",
    "MSK_RES_ERR_CBF_NO_VERSION_SPECIFIED", "MSK_RES_ERR_CBF_SYNTAX",
    "MSK_RES_ERR_CBF_DUPLICATE_OBJ", "MSK_RES_ERR_CBF_DUPLICATE_CON",
    "MSK_RES_ERR_CBF_DUPLICATE_VAR", "MSK_RES_ERR_CBF_DUPLICATE_INT",
    "MSK_RES_ERR_CBF_INVALID_VAR_TYPE", "MSK_RES_ERR_CBF_INVALID_CON_TYPE",
    "MSK_RES_ERR_CBF_INVALID_DOMAIN_DIMENSION", "MSK_RES_ERR_CBF_DUPLICATE_OBJACOORD",
    "MSK_RES_ERR_CBF_DUPLICATE_BCOORD", "MSK_RES_ERR_CBF_DUPLICATE_ACOORD",
    "MSK_RES_ERR_CBF_TOO_FEW_VARIABLES", "MSK_RES_ERR_CBF_TOO_FEW_CONSTRAINTS",
    "MSK_RES_ERR_CBF_TOO_FEW_INTS", "MSK_RES_ERR_CBF_TOO_MANY_INTS",
    "MSK_RES_ERR_CBF_INVALID_INT_INDEX", "MSK_RES_ERR_CBF_UNSUPPORTED",
    "MSK_RES_ERR_CBF_DUPLICATE_PSDVAR", "MSK_RES_ERR_CBF_INVALID_PSDVAR_DIMENSION",
    "MSK_RES_ERR_CBF_TOO_FEW_PSDVAR", "MSK_RES_ERR_CBF_INVALID_EXP_DIMENSION",
    "MSK_RES_ERR_CBF_DUPLICATE_POW_CONES", "MSK_RES_ERR_CBF_DUPLICATE_POW_STAR_CONES",
    "MSK_RES_ERR_CBF_INVALID_POWER", "MSK_RES_ERR_CBF_POWER_CONE_IS_TOO_LONG",
    "MSK_RES_ERR_CBF_INVALID_POWER_CONE_INDEX",
    "MSK_RES_ERR_CBF_INVALID_POWER_STAR_CONE_INDEX",
    "MSK_RES_ERR_CBF_UNHANDLED_POWER_CONE_TYPE",
    "MSK_RES_ERR_CBF_UNHANDLED_POWER_STAR_CONE_TYPE", "MSK_RES_ERR_CBF_POWER_CONE_MISMATCH",
    "MSK_RES_ERR_CBF_POWER_STAR_CONE_MISMATCH", "MSK_RES_ERR_CBF_INVALID_NUMBER_OF_CONES",
    "MSK_RES_ERR_CBF_INVALID_DIMENSION_OF_CONES", "MSK_RES_ERR_CBF_INVALID_NUM_OBJACOORD",
    "MSK_RES_ERR_CBF_INVALID_NUM_OBJFCOORD", "MSK_RES_ERR_CBF_INVALID_NUM_ACOORD",
    "MSK_RES_ERR_CBF_INVALID_NUM_BCOORD", "MSK_RES_ERR_CBF_INVALID_NUM_FCOORD",
    "MSK_RES_ERR_CBF_INVALID_NUM_HCOORD", "MSK_RES_ERR_CBF_INVALID_NUM_DCOORD",
    "MSK_RES_ERR_CBF_EXPECTED_A_KEYWORD", "MSK_RES_ERR_CBF_INVALID_NUM_PSDCON",
    "MSK_RES_ERR_CBF_DUPLICATE_PSDCON", "MSK_RES_ERR_CBF_INVALID_DIMENSION_OF_PSDCON",
    "MSK_RES_ERR_CBF_INVALID_PSDCON_INDEX", "MSK_RES_ERR_CBF_INVALID_PSDCON_VARIABLE_INDEX",
    "MSK_RES_ERR_CBF_INVALID_PSDCON_BLOCK_INDEX", "MSK_RES_ERR_CBF_UNSUPPORTED_CHANGE",
    "MSK_RES_ERR_MIO_INVALID_ROOT_OPTIMIZER", "MSK_RES_ERR_MIO_INVALID_NODE_OPTIMIZER",
    "MSK_RES_ERR_MPS_WRITE_CPLEX_INVALID_CONE_TYPE", "MSK_RES_ERR_TOCONIC_CONSTR_Q_NOT_PSD",
    "MSK_RES_ERR_TOCONIC_CONSTRAINT_FX", "MSK_RES_ERR_TOCONIC_CONSTRAINT_RA",
    "MSK_RES_ERR_TOCONIC_CONSTR_NOT_CONIC", "MSK_RES_ERR_TOCONIC_OBJECTIVE_NOT_PSD",
    "MSK_RES_ERR_GETDUAL_NOT_AVAILABLE", "MSK_RES_ERR_SERVER_CONNECT",
    "MSK_RES_ERR_SERVER_PROTOCOL", "MSK_RES_ERR_SERVER_STATUS", "MSK_RES_ERR_SERVER_TOKEN",
    "MSK_RES_ERR_SERVER_ADDRESS", "MSK_RES_ERR_SERVER_CERTIFICATE",
    "MSK_RES_ERR_SERVER_TLS_CLIENT", "MSK_RES_ERR_SERVER_ACCESS_TOKEN",
    "MSK_RES_ERR_SERVER_PROBLEM_SIZE", "MSK_RES_ERR_SERVER_HARD_TIMEOUT",
    "MSK_RES_ERR_DUPLICATE_INDEX_IN_A_SPARSE_MATRIX",
    "MSK_RES_ERR_DUPLICATE_INDEX_IN_AFEIDX_LIST", "MSK_RES_ERR_DUPLICATE_FIJ",
    "MSK_RES_ERR_INVALID_FIJ", "MSK_RES_ERR_HUGE_FIJ", "MSK_RES_ERR_INVALID_G",
    "MSK_RES_ERR_INVALID_B", "MSK_RES_ERR_DOMAIN_INVALID_INDEX",
    "MSK_RES_ERR_DOMAIN_DIMENSION", "MSK_RES_ERR_DOMAIN_DIMENSION_PSD",
    "MSK_RES_ERR_NOT_POWER_DOMAIN", "MSK_RES_ERR_DOMAIN_POWER_INVALID_ALPHA",
    "MSK_RES_ERR_DOMAIN_POWER_NEGATIVE_ALPHA", "MSK_RES_ERR_DOMAIN_POWER_NLEFT",
    "MSK_RES_ERR_AFE_INVALID_INDEX", "MSK_RES_ERR_ACC_INVALID_INDEX",
    "MSK_RES_ERR_ACC_INVALID_ENTRY_INDEX", "MSK_RES_ERR_ACC_AFE_DOMAIN_MISMATCH",
    "MSK_RES_ERR_DJC_INVALID_INDEX", "MSK_RES_ERR_DJC_UNSUPPORTED_DOMAIN_TYPE",
    "MSK_RES_ERR_DJC_AFE_DOMAIN_MISMATCH", "MSK_RES_ERR_DJC_INVALID_TERM_SIZE",
    "MSK_RES_ERR_DJC_DOMAIN_TERMSIZE_MISMATCH", "MSK_RES_ERR_DJC_TOTAL_NUM_TERMS_MISMATCH",
    "MSK_RES_ERR_UNDEF_SOLUTION", "MSK_RES_ERR_NO_DOTY", "MSK_RES_TRM_MAX_ITERATIONS",
    "MSK_RES_TRM_MAX_TIME", "MSK_RES_TRM_OBJECTIVE_RANGE", "MSK_RES_TRM_MIO_NUM_RELAXS",
    "MSK_RES_TRM_MIO_NUM_BRANCHES", "MSK_RES_TRM_NUM_MAX_NUM_INT_SOLUTIONS",
    "MSK_RES_TRM_STALL", "MSK_RES_TRM_USER_CALLBACK", "MSK_RES_TRM_MAX_NUM_SETBACKS",
    "MSK_RES_TRM_NUMERICAL_PROBLEM", "MSK_RES_TRM_LOST_RACE", "MSK_RES_TRM_INTERNAL",
    "MSK_RES_TRM_INTERNAL_STOP", "MSK_RES_TRM_SERVER_MAX_TIME",
    "MSK_RES_TRM_SERVER_MAX_MEMORY", "MSK_RESPONSE_OK", "MSK_RESPONSE_WRN", "MSK_RESPONSE_TRM",
    "MSK_RESPONSE_ERR", "MSK_RESPONSE_UNK", "MSK_SCALING_FREE", "MSK_SCALING_NONE",
    "MSK_SCALING_METHOD_POW2", "MSK_SCALING_METHOD_FREE", "MSK_SENSITIVITY_TYPE_BASIS",
    "MSK_SIM_SELECTION_FREE", "MSK_SIM_SELECTION_FULL", "MSK_SIM_SELECTION_ASE",
    "MSK_SIM_SELECTION_DEVEX", "MSK_SIM_SELECTION_SE", "MSK_SIM_SELECTION_PARTIAL",
    "MSK_SOL_ITEM_XC", "MSK_SOL_ITEM_XX", "MSK_SOL_ITEM_Y", "MSK_SOL_ITEM_SLC",
    "MSK_SOL_ITEM_SUC", "MSK_SOL_ITEM_SLX", "MSK_SOL_ITEM_SUX", "MSK_SOL_ITEM_SNX",
    "MSK_SOL_STA_UNKNOWN", "MSK_SOL_STA_OPTIMAL", "MSK_SOL_STA_PRIM_FEAS",
    "MSK_SOL_STA_DUAL_FEAS", "MSK_SOL_STA_PRIM_AND_DUAL_FEAS", "MSK_SOL_STA_PRIM_INFEAS_CER",
    "MSK_SOL_STA_DUAL_INFEAS_CER", "MSK_SOL_STA_PRIM_ILLPOSED_CER",
    "MSK_SOL_STA_DUAL_ILLPOSED_CER", "MSK_SOL_STA_INTEGER_OPTIMAL", "MSK_SOL_BAS",
    "MSK_SOL_ITR", "MSK_SOL_ITG", "MSK_SOLVE_FREE", "MSK_SOLVE_PRIMAL", "MSK_SOLVE_DUAL",
    "MSK_SPAR_DATA_FILE_NAME", "MSK_SPAR_PARAM_READ_FILE_NAME",
    "MSK_SPAR_PARAM_WRITE_FILE_NAME", "MSK_SPAR_PARAM_COMMENT_SIGN",
    "MSK_SPAR_DEBUG_FILE_NAME", "MSK_SPAR_BAS_SOL_FILE_NAME", "MSK_SPAR_ITR_SOL_FILE_NAME",
    "MSK_SPAR_INT_SOL_FILE_NAME", "MSK_SPAR_SOL_FILTER_XC_LOW", "MSK_SPAR_SOL_FILTER_XC_UPR",
    "MSK_SPAR_SOL_FILTER_XX_LOW", "MSK_SPAR_SOL_FILTER_XX_UPR", "MSK_SPAR_READ_MPS_OBJ_NAME",
    "MSK_SPAR_READ_MPS_RAN_NAME", "MSK_SPAR_READ_MPS_RHS_NAME", "MSK_SPAR_READ_MPS_BOU_NAME",
    "MSK_SPAR_STAT_NAME", "MSK_SPAR_STAT_KEY", "MSK_SPAR_SENSITIVITY_RES_FILE_NAME",
    "MSK_SPAR_SENSITIVITY_FILE_NAME", "MSK_SPAR_MIO_DEBUG_STRING",
    "MSK_SPAR_REMOTE_OPTSERVER_HOST", "MSK_SPAR_REMOTE_TLS_CERT_PATH",
    "MSK_SPAR_REMOTE_TLS_CERT", "MSK_SK_UNK", "MSK_SK_BAS", "MSK_SK_SUPBAS", "MSK_SK_LOW",
    "MSK_SK_UPR", "MSK_SK_FIX", "MSK_SK_INF", "MSK_STARTING_POINT_FREE",
    "MSK_STARTING_POINT_GUESS", "MSK_STARTING_POINT_CONSTANT", "MSK_STREAM_LOG",
    "MSK_STREAM_MSG", "MSK_STREAM_ERR", "MSK_STREAM_WRN", "MSK_MAX_STR_LEN",
    "MSK_LICENSE_BUFFER_LENGTH", "MSK_VAR_TYPE_CONT", "MSK_VAR_TYPE_INT"
};
static const int symbcon_values[PRIMAL_SYMB_N] = {
    0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 0, 1, 0, 1, 2, 3, 4, 0, 1, 0, 1, 1, 0, 2, 3, 1, 0, 2,
    0, 1, 2, 0, 1, 2, 3, 29, 88, 66, 31, 69, 19, 56, 7, 44, 8, 10, 47, 12, 74, 49, 9, 72, 46,
    11, 73, 48, 45, 20, 102, 57, 15, 90, 52, 1, 34, 38, 93, 36, 0, 37, 14, 51, 21, 103, 58, 2,
    99, 39, 18, 92, 55, 26, 105, 63, 6, 101, 43, 68, 17, 80, 91, 54, 97, 35, 30, 89, 106, 5,
    77, 100, 42, 25, 86, 104, 62, 67, 13, 50, 85, 76, 82, 83, 81, 24, 61, 4, 41, 23, 60, 3, 40,
    16, 53, 78, 27, 94, 64, 32, 70, 22, 59, 28, 87, 65, 33, 71, 96, 79, 84, 95, 107, 98, 75, 0,
    1, 2, 3, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 0, 0, 1,
    2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 0, 4, 3, 2, 1, 7, 8, 6, 5, 9, 19, 16, 18, 13, 17, 12, 15,
    66, 65, 62, 64, 63, 47, 43, 42, 44, 114, 24, 30, 37, 36, 38, 35, 48, 23, 21, 32, 27, 29,
    34, 41, 22, 20, 31, 26, 28, 33, 40, 39, 45, 50, 49, 53, 46, 25, 51, 52, 11, 10, 60, 115,
    108, 111, 113, 110, 112, 109, 92, 95, 97, 94, 96, 93, 105, 106, 99, 107, 100, 103, 101,
    104, 102, 98, 78, 79, 80, 67, 68, 69, 75, 76, 70, 77, 71, 73, 72, 74, 84, 87, 91, 86, 88,
    85, 90, 89, 82, 83, 81, 54, 14, 57, 56, 59, 58, 55, 61, 0, 1, 12, 11, 8, 7, 4, 6, 5, 9, 10,
    13, 14, 57, 50, 49, 38, 62, 63, 39, 35, 37, 58, 36, 32, 33, 28, 31, 30, 21, 20, 16, 18, 19,
    17, 27, 26, 22, 24, 25, 23, 34, 29, 42, 43, 48, 44, 45, 41, 40, 60, 59, 3, 2, 1, 55, 52,
    54, 51, 53, 15, 61, 46, 0, 56, 47, 2, 0, 1, 10, 15, 11, 16, 12, 14, 13, 5, 4, 3, 9, 8, 6,
    7, 17, 19, 18, 20, 21, 0, 3, 5, 4, 1, 2, 6, 12, 14, 13, 9, 10, 8, 7, 11, 106, 107, 17, 16,
    19, 41, 81, 65, 75, 70, 67, 68, 79, 80, 77, 72, 78, 74, 69, 66, 76, 71, 73, 99, 83, 93, 88,
    85, 86, 97, 98, 95, 90, 96, 92, 87, 84, 94, 89, 91, 39, 23, 33, 28, 25, 26, 37, 38, 35, 30,
    36, 32, 27, 24, 34, 29, 31, 21, 22, 40, 47, 82, 42, 48, 64, 46, 50, 51, 43, 101, 53, 52,
    55, 56, 54, 57, 102, 59, 58, 61, 62, 60, 63, 49, 45, 44, 103, 100, 20, 15, 116, 111, 115,
    110, 113, 114, 117, 120, 119, 128, 121, 18, 127, 124, 125, 126, 118, 134, 135, 130, 131,
    132, 133, 122, 123, 104, 105, 136, 112, 129, 109, 108, 0, 1, 2, 0, 1, 2, 3, 134, 19, 100,
    167, 98, 56, 110, 150, 8, 32, 42, 38, 35, 45, 36, 37, 5, 28, 18, 26, 27, 44, 20, 22, 24,
    23, 17, 6, 7, 21, 121, 49, 118, 116, 119, 114, 113, 120, 11, 139, 152, 52, 53, 54, 13, 154,
    155, 142, 143, 147, 146, 156, 161, 81, 46, 47, 75, 74, 76, 77, 78, 83, 96, 80, 72, 88, 95,
    70, 58, 87, 84, 79, 68, 97, 57, 93, 82, 86, 89, 94, 59, 90, 69, 127, 168, 129, 130, 182,
    131, 128, 173, 174, 172, 183, 181, 180, 179, 187, 186, 185, 188, 184, 170, 169, 171, 177,
    176, 178, 165, 166, 15, 16, 14, 43, 33, 31, 30, 29, 164, 34, 39, 41, 48, 50, 51, 132, 111,
    112, 159, 160, 153, 141, 148, 145, 137, 151, 138, 157, 144, 158, 149, 140, 55, 103, 102,
    104, 105, 101, 109, 106, 107, 108, 126, 125, 123, 124, 122, 63, 62, 65, 66, 64, 67, 136,
    60, 117, 115, 135, 40, 9, 25, 162, 163, 175, 2, 0, 1, 4, 10, 92, 91, 61, 85, 71, 73, 99,
    133, 12, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 0, 1, 2, 0, 1, 2, 3, 0, 1, 0, 1, 2, 3,
    0, 1, 2, 0, 1, 2, 3, 0, 1, 1, 0, 2, 4, 0, 8, 1, 7, 6, 3, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 0,
    1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 50, 51, 52, 53,
    54, 57, 62, 63, 65, 66, 70, 71, 72, 80, 85, 200, 201, 250, 251, 270, 300, 350, 351, 352,
    400, 405, 500, 501, 502, 503, 504, 505, 509, 510, 511, 512, 515, 516, 705, 710, 800, 801,
    802, 803, 830, 831, 850, 851, 852, 853, 900, 901, 902, 903, 904, 930, 940, 950, 960, 970,
    980, 981, 1000, 1001, 1002, 1003, 1005, 1006, 1007, 1008, 1010, 1011, 1012, 1013, 1014,
    1015, 1016, 1017, 1018, 1019, 1020, 1021, 1025, 1026, 1027, 1028, 1035, 1036, 1040, 1045,
    1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1059, 1060, 1061,
    1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076,
    1077, 1078, 1079, 1080, 1081, 1082, 1083, 1089, 1090, 1091, 1092, 1093, 1094, 1100, 1101,
    1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110, 1111, 1112, 1113, 1114, 1115, 1116,
    1117, 1118, 1119, 1120, 1121, 1122, 1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132, 1133,
    1134, 1136, 1137, 1138, 1139, 1140, 1141, 1142, 1143, 1144, 1146, 1151, 1153, 1154, 1156,
    1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1170, 1175, 1176, 1177,
    1178, 1179, 1180, 1181, 1182, 1183, 1184, 1197, 1198, 1199, 1200, 1201, 1202, 1203, 1204,
    1205, 1206, 1207, 1208, 1209, 1210, 1215, 1216, 1217, 1218, 1219, 1220, 1221, 1222, 1225,
    1226, 1227, 1228, 1230, 1231, 1232, 1234, 1235, 1236, 1237, 1238, 1240, 1241, 1242, 1243,
    1245, 1246, 1247, 1248, 1250, 1251, 1252, 1253, 1254, 1255, 1256, 1257, 1258, 1259, 1260,
    1261, 1262, 1263, 1264, 1266, 1267, 1268, 1274, 1269, 1270, 1271, 1272, 1275, 1280, 1281,
    1283, 1285, 1286, 1287, 1288, 1289, 1290, 1291, 1292, 1293, 1294, 1295, 1296, 1299, 1300,
    1301, 1302, 1303, 1304, 1305, 1306, 1307, 1310, 1311, 1320, 1350, 1375, 1380, 1385, 1390,
    1391, 1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1408, 1409, 1415, 1417, 1420, 1421,
    1445, 1446, 1449, 1450, 1451, 1461, 1462, 1469, 1470, 1471, 1472, 1473, 1474, 1480, 1482,
    1500, 1501, 1503, 1550, 1551, 1552, 1560, 1570, 1571, 1572, 1573, 1578, 1580, 1590, 1600,
    1610, 1615, 1650, 1700, 1701, 1702, 1710, 1711, 1750, 1760, 1800, 1801, 2000, 2001, 2500,
    2501, 2502, 2503, 2504, 2560, 2561, 2562, 2563, 2564, 2800, 2900, 2901, 2950, 2953, 3000,
    3001, 3002, 3005, 3999, 3050, 3051, 3052, 3053, 3054, 3055, 3056, 3057, 3058, 3080, 3100,
    3101, 3102, 3500, 3800, 3910, 3915, 3916, 3920, 3940, 3941, 3942, 3943, 3944, 3950, 4000,
    4001, 4002, 4003, 4005, 4006, 4010, 4011, 4012, 4500, 4501, 4502, 4503, 4504, 4505, 5000,
    5004, 5005, 5010, 6000, 6010, 6020, 7000, 7001, 7002, 7005, 7010, 7011, 7012, 7015, 7016,
    7017, 7018, 7019, 7100, 7101, 7102, 7103, 7104, 7105, 7106, 7107, 7108, 7110, 7111, 7112,
    7113, 7114, 7115, 7116, 7117, 7118, 7119, 7120, 7121, 7122, 7123, 7124, 7125, 7126, 7127,
    7130, 7131, 7132, 7133, 7134, 7135, 7136, 7137, 7138, 7139, 7140, 7141, 7150, 7151, 7152,
    7153, 7155, 7156, 7157, 7158, 7200, 7201, 7202, 7203, 7204, 7205, 7210, 7700, 7701, 7750,
    7800, 7801, 7802, 7803, 7804, 7820, 8000, 8001, 8002, 8003, 8004, 8005, 8006, 8007, 8008,
    8009, 20050, 20060, 20100, 20101, 20102, 20103, 20150, 20400, 20401, 20402, 20403, 20404,
    20405, 20406, 20500, 20600, 20601, 20602, 20700, 20701, 20702, 20703, 20704, 20705, 22000,
    22010, 100000, 100001, 100002, 100008, 100009, 100015, 100006, 100007, 100020, 100025,
    100027, 100030, 100031, 100032, 100033, 0, 1, 2, 3, 4, 0, 1, 0, 1, 0, 0, 1, 2, 3, 4, 5, 0,
    1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 0, 2, 0, 1, 2, 1, 7, 8, 6, 2, 0, 4,
    3, 18, 19, 20, 21, 10, 11, 12, 9, 23, 22, 17, 16, 5, 13, 15, 14, 0, 1, 2, 3, 4, 5, 6, 0, 1,
    2, 0, 1, 2, 3, 1024, 21, 0, 1
};

/* Report the symbolic-constant table size and max name length. */
PRIMALrescodee PRIMAL_getsymbcondim(PRIMALenv_t env, int *num, size_t *maxlen) {
    if (!env || !num || !maxlen) return PRIMAL_RES_ERR_NULL;
    *num = PRIMAL_SYMB_N;
    *maxlen = PRIMAL_SYMB_MAXLEN;
    return PRIMAL_RES_OK;
}

/* Return the name and value of symbolic constant i; sizevalue is unused. */
PRIMALrescodee PRIMAL_getsymbcon(PRIMALtask_t t, int i, int sizevalue, char *name,
                                 int *value) {
    if (!t || !name || !value) return PRIMAL_RES_ERR_NULL;
    if (i < 0 || i >= PRIMAL_SYMB_N) return PRIMAL_RES_ERR_ARG;
    (void)sizevalue;   /* the reference documents it as the length of the
                        * `value` buffer, which here is an int: no effect */
    strcpy(name, symbcon_names[i]);   /* the caller allocates >= MAXLEN+1 */
    *value = symbcon_values[i];
    return PRIMAL_RES_OK;
}

/* Look up a symbolic name and write its value as a decimal string; 0 if
 * unknown. */
int PRIMAL_symnamtovalue(const char *name, char *value) {
    if (!name || !value) return 0;
    for (int i = 0; i < PRIMAL_SYMB_N; i++) {
        if (strcmp(symbcon_names[i], name) == 0) {
            snprintf(value, 16, "%d", symbcon_values[i]);   /* an int fits in 12 */
            return 1;
        }
    }
    return 0;
}

/* Write the reference's symbolic name for an int parameter value; "" when
 * there is none. */
PRIMALrescodee PRIMAL_iparvaltosymnam(PRIMALenv_t env, int whichparam, int whichvalue,
                                      char *symbolicname) {
    if (!env || !symbolicname) return PRIMAL_RES_ERR_NULL;
    symbolicname[0] = '\0';
    /* The optimizer values use the reference's numbering. */
    if (whichparam == PRIMAL_IPAR_OPTIMIZER) {
        static const char *const opt[9] = {
            "MSK_OPTIMIZER_CONIC", "MSK_OPTIMIZER_DUAL_SIMPLEX", "MSK_OPTIMIZER_FREE",
            "MSK_OPTIMIZER_FREE_SIMPLEX", "MSK_OPTIMIZER_INTPNT", "MSK_OPTIMIZER_MIXED_INT",
            "MSK_OPTIMIZER_NEW_DUAL_SIMPLEX", "MSK_OPTIMIZER_NEW_PRIMAL_SIMPLEX",
            "MSK_OPTIMIZER_PRIMAL_SIMPLEX" };
        if (whichvalue >= 0 && whichvalue < 9) strcpy(symbolicname, opt[whichvalue]);
        return PRIMAL_RES_OK;
    }
    /* This solver's boolean parameters use the reference's ON/OFF names. */
    if (whichparam == PRIMAL_IPAR_PRESOLVE || whichparam == PRIMAL_IPAR_SCALING) {
        if (whichvalue == 0) strcpy(symbolicname, "MSK_OFF");
        else if (whichvalue == 1) strcpy(symbolicname, "MSK_ON");
        return PRIMAL_RES_OK;
    }
    /* No symbolic name: the reference writes "" (measured). */
    return PRIMAL_RES_OK;
}

/* Name as a string of an information item and of a callback code (reference
 * dinfitemtostr/iinfitemtostr/liinfitemtostr/callbackcodetostr). No task: they
 * are the name tables already extracted from the reference. An index out of
 * domain is ERR_ARG, a callback code without a name is ERR_ARG. */
PRIMALrescodee PRIMAL_dinfitemtostr(PRIMALdinfiteme item, char *str) {
    if (!str) return PRIMAL_RES_ERR_NULL;
    if ((int)item < 0 || (int)item >= PRIMAL_DINF_END) return PRIMAL_RES_ERR_ARG;
    strcpy(str, dinf_names[(int)item]);
    return PRIMAL_RES_OK;
}
/* Copy the name of an int information item into str. */
PRIMALrescodee PRIMAL_iinfitemtostr(PRIMALiinfiteme item, char *str) {
    if (!str) return PRIMAL_RES_ERR_NULL;
    if ((int)item < 0 || (int)item >= PRIMAL_IINF_END) return PRIMAL_RES_ERR_ARG;
    strcpy(str, iinf_names[(int)item]);
    return PRIMAL_RES_OK;
}
/* Copy the name of a 64-bit information item into str. */
PRIMALrescodee PRIMAL_liinfitemtostr(PRIMALliinfiteme item, char *str) {
    if (!str) return PRIMAL_RES_ERR_NULL;
    if ((int)item < 0 || (int)item >= PRIMAL_LIINF_END) return PRIMAL_RES_ERR_ARG;
    strcpy(str, liinf_names[(int)item]);
    return PRIMAL_RES_OK;
}
/* Copy the name of a callback code from the symbolic table, or ERR_ARG. */
PRIMALrescodee PRIMAL_callbackcodetostr(PRIMALcallbackcodee code, char *str) {
    if (!str) return PRIMAL_RES_ERR_NULL;
    /* The code's name is one of the reference symbols: it is searched in the
     * symbolic-constants table by value, among the MSK_CALLBACK_* only. */
    for (int i = 0; i < PRIMAL_SYMB_N; i++) {
        if (symbcon_values[i] == (int)code &&
            strncmp(symbcon_names[i], "MSK_CALLBACK_", 13) == 0) {
            strcpy(str, symbcon_names[i]);
            return PRIMAL_RES_OK;
        }
    }
    return PRIMAL_RES_ERR_ARG;
}

/* analyzenames: checks that the model names are valid for the requested type.
 * The reference distinguishes the codes (INVALID_VAR_NAME=1077,
 * INVALID_CON_NAME=1076, BLANK_NAME=1070, DUP_NAME=1071); here a name that is
 * not valid is ERR_ARG (our code space, declared deviation). The rule applied:
 * for MPS/LP a non-empty name cannot contain spaces (they are the format
 * delimiters), and duplicates are already impossible because name_put refuses
 * them at write time. */
PRIMALrescodee PRIMAL_analyzenames(PRIMALtask_t t, PRIMALstreamtypee whichstream,
                                   PRIMALnametypee nametype) {
    if (!t) return PRIMAL_RES_ERR_NULL;
    (void)whichstream;
    if (nametype != PRIMAL_NAME_TYPE_MPS && nametype != PRIMAL_NAME_TYPE_LP)
        return PRIMAL_RES_OK;   /* TYPE_GEN: no format restriction */
    for (int j = 0; j < t->numvar; j++)
        if (t->varname[j] && t->varname[j][0] && strpbrk(t->varname[j], " \t"))
            return PRIMAL_RES_ERR_ARG;
    for (int i = 0; i < t->numcon; i++)
        if (t->conname[i] && t->conname[i][0] && strpbrk(t->conname[i], " \t"))
            return PRIMAL_RES_ERR_ARG;
    for (int k = 0; k < t->numcones; k++)
        if (t->conename[k] && t->conename[k][0] && strpbrk(t->conename[k], " \t"))
            return PRIMAL_RES_ERR_ARG;
    for (int j = 0; j < t->numbarvar; j++)
        if (t->barname[j] && t->barname[j][0] && strpbrk(t->barname[j], " \t"))
            return PRIMAL_RES_ERR_ARG;
    if (t->objname && t->objname[0] && strpbrk(t->objname, " \t"))
        return PRIMAL_RES_ERR_ARG;
    return PRIMAL_RES_OK;
}

/* No string parameters exist: always ERR_ARG. */
PRIMALrescodee PRIMAL_getstrparamal(PRIMALtask_t t, int param, int numaddchr, char **value) {
    if (!t || !value) return PRIMAL_RES_ERR_NULL;
    (void)param; (void)numaddchr;
    return PRIMAL_RES_ERR_ARG;   /* no string parameters */
}
/* No string parameters exist: always ERR_ARG. */
PRIMALrescodee PRIMAL_getnastrparamal(PRIMALtask_t t, const char *paramname, int numaddchr,
                                      char **value) {
    if (!t || !paramname || !value) return PRIMAL_RES_ERR_NULL;
    (void)numaddchr;
    return PRIMAL_RES_ERR_ARG;   /* no string parameters */
}
